// src/views/auth/password-reset-request.tsx
import React, { useEffect, useRef, useState } from "react";
import { flushSync } from "react-dom";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faEnvelope, faUser, faArrowLeft } from "@fortawesome/free-solid-svg-icons";
import Button, { ButtonColor } from "../../components/Button/Button";
import FormInput from "../../components/FormInput";
import { useRequestPasswordReset } from "../../hooks/useRequestPasswordReset";
import { type RequestPasswordResetInput } from "../../gql/graphql";

const PasswordResetRequest: React.FC = () => {
  const [formData, setFormData] = useState<RequestPasswordResetInput>({ username: "", email: "" });
  const [errorMessage, setErrorMessage] = useState<string>("");
  const [submitted, setSubmitted] = useState(false);

  // HARD BLOCK: once true, stays true until an error occurs
  const blockedRef = useRef(false);
  const [blocked, setBlocked] = useState(false);

  const mutation = useRequestPasswordReset();

  // Swallow Enter/Space globally while blocked (captures before anything else)
  useEffect(() => {
    const onKeyDown = (e: KeyboardEvent) => {
      if (!blockedRef.current) return;
      const k = e.key;
      if (k === "Enter" || k === " " || k === "Spacebar") {
        e.preventDefault();
        e.stopPropagation();
      }
    };
    document.addEventListener("keydown", onKeyDown, true);
    return () => document.removeEventListener("keydown", onKeyDown, true);
  }, []);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
    if (errorMessage) setErrorMessage("");
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (blockedRef.current || submitted) return;

    if (!formData.username.trim() || !formData.email.trim()) {
      setErrorMessage("Please fill in all fields");
      return;
    }

    setErrorMessage("");
    blockedRef.current = true;
    setBlocked(true);

    try {
      const ok = await mutation.mutateAsync({ input: formData });

      if (ok) {
        // Flip view synchronously; keep blocked = true (form is gone)
        flushSync(() => setSubmitted(true));
        return;
      }

      // Treat falsy as error → unblock to let user retry
      setErrorMessage("Failed to send password reset email. Please try again.");
      blockedRef.current = false;
      setBlocked(false);
    } catch (err: any) {
      console.error("Password reset request failed:", err);
      setErrorMessage(err?.message || "Failed to send password reset email. Please try again.");
      blockedRef.current = false;
      setBlocked(false);
    }
  };

  const disabled = blocked || submitted;

  if (submitted) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-900 py-12 px-4 sm:px-6 lg:px-8">
        <div className="max-w-md w-full space-y-8">
          <div className="text-center">
            <div className="mx-auto h-12 w-12 bg-green-100 dark:bg-green-900 rounded-full flex items-center justify-center mb-4">
              <FontAwesomeIcon icon={faEnvelope} className="text-green-600 dark:text-green-400 text-xl" />
            </div>
            <h2 className="text-3xl font-bold text-gray-900 dark:text-gray-100">Check your email</h2>
            <p className="mt-4 text-gray-600 dark:text-gray-400">
              We've sent a password reset link to <strong>{formData.email}</strong>
            </p>
            <p className="mt-2 text-sm text-gray-500 dark:text-gray-500">
              Please check your email and follow the instructions to reset your password.
            </p>
          </div>
          <div className="mt-8">
            <a
              href="/"
              className="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100 transition-colors"
            >
              <FontAwesomeIcon icon={faArrowLeft} className="mr-2" />
              Back to Home
            </a>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-900 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-md w-full space-y-8 relative">
        {/* Click/press guard overlay while blocked */}
        {blocked && <div className="absolute inset-0 z-10 bg-transparent" aria-hidden="true" />}

        <div>
          <div className="mx-auto h-12 w-12 bg-blue-100 dark:bg-blue-900 rounded-full flex items-center justify-center">
            <FontAwesomeIcon icon={faEnvelope} className="text-blue-600 dark:text-blue-400 text-xl" />
          </div>
          <h2 className="mt-6 text-center text-3xl font-bold text-gray-900 dark:text-gray-100">Reset your password</h2>
          <p className="mt-2 text-center text-sm text-gray-600 dark:text-gray-400">
            Enter your username and email address to receive a password reset link
          </p>
        </div>

        <form
          className="mt-8 space-y-6 relative"
          onSubmit={handleSubmit}
          onKeyDownCapture={e => {
            if (blockedRef.current && e.key === "Enter") {
              e.preventDefault();
              e.stopPropagation();
            }
          }}
          noValidate
        >
          {/* Disable whole form while blocked */}
          <fieldset
            disabled={disabled}
            aria-busy={blocked}
            className={disabled ? "opacity-60 pointer-events-none" : ""}
          >
            <div className="space-y-4">
              <FormInput
                id="username"
                name="username"
                type="text"
                value={formData.username}
                onChange={handleInputChange}
                placeholder="Username"
                label="Username"
                icon={faUser}
                required
              />

              <FormInput
                id="email"
                name="email"
                type="email"
                value={formData.email}
                onChange={handleInputChange}
                placeholder="Email address"
                label="Email address"
                icon={faEnvelope}
                required
              />
            </div>

            {errorMessage && (
              <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-md p-3 mt-4">
                <p className="text-sm text-red-600 dark:text-red-400">{errorMessage}</p>
              </div>
            )}

            <div className="mt-4">
              <Button
                color={ButtonColor.blue}
                label={blocked ? "Sending…" : "Send Reset Link"}
                showLabel
                status={blocked ? "loading" : "idle"}
                className="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md"
                aria-disabled={disabled}
              />
            </div>

            <div className="text-center mt-2">
              <a
                href="/"
                className="text-sm text-blue-600 dark:text-blue-400 hover:text-blue-500 dark:hover:text-blue-300 transition-colors"
              >
                ← Back to Home
              </a>
            </div>
          </fieldset>
        </form>
      </div>
    </div>
  );
};

export default PasswordResetRequest;

// src/routes/auth/password-reset-request/+page.svelte
<script lang="ts">
  import Seo from '$lib/Seo.svelte';
  import { faEnvelope, faUser } from '@fortawesome/free-solid-svg-icons';
  import AuthCard from '../../../svelte/components/AuthCard.svelte';
  import ErrorBanner from '../../../svelte/components/ErrorBanner.svelte';
  import FormInput from '../../../svelte/components/FormInput.svelte';
  import { PasswordResetRequestBloc } from '../../../svelte/components/PasswordResetRequest.bloc.svelte';

  /**
   * "I forgot my password".
   *
   * A view over `PasswordResetRequestBloc`. It used to hand-roll a Tailwind
   * lookalike of the auth shell and boot its own TanStack client through a
   * dynamic import before it could render anything; the request is one call
   * with nothing observing it, so it goes direct and the form renders on the
   * server like every other auth screen.
   */
  let { bloc = new PasswordResetRequestBloc() }: { bloc?: PasswordResetRequestBloc } = $props();

  const iconUser = faUser;
  const iconEnvelope = faEnvelope;

  function handleSubmit(event: Event) {
    event.preventDefault();
    void bloc.submit();
  }
</script>

<Seo title="Reset Password" />

<svelte:document onkeydown={(event) => bloc.handleKeyDown(event)} />

{#if bloc.submitted}
  <AuthCard title="Check your email">
    {#snippet media()}
      <div class="glyph good" aria-hidden="true">
        <svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">
          <rect x="2.5" y="5" width="19" height="14" rx="2.5" />
          <path d="M3 7l9 6 9-6" />
        </svg>
      </div>
    {/snippet}

    {#snippet children()}
      <p class="lede">
        We've sent a password reset link to <b>{bloc.email}</b>
      </p>
      <p class="hint">
        Please check your email and follow the instructions to reset your password.
      </p>
      <a class="btn-ghost" href="/">Back to home</a>
    {/snippet}
  </AuthCard>
{:else}
  <AuthCard
    title="Reset your password"
    subtitle="Enter your username and email address to receive a password reset link"
  >
    {#snippet media()}
      <div class="glyph" aria-hidden="true">
        <svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">
          <rect x="2.5" y="5" width="19" height="14" rx="2.5" />
          <path d="M3 7l9 6 9-6" />
        </svg>
      </div>
    {/snippet}

    {#snippet children()}
      <form class="pr-form" onsubmit={handleSubmit} aria-busy={bloc.isSubmitting} novalidate>
        <!-- One fieldset rather than a per-control `disabled`: it also takes
             the fields out of the tab order while the request is in flight,
             which is how the old screen let a second Enter send a second email. -->
        <fieldset disabled={bloc.isDisabled}>
          <FormInput
            id="username"
            name="username"
            type="text"
            value={bloc.username}
            onInput={(detail) => bloc.updateField('username', detail.value)}
            placeholder="Username"
            label="Username"
            icon={iconUser}
            required
            disabled={bloc.isDisabled}
          />

          <FormInput
            id="email"
            name="email"
            type="email"
            value={bloc.email}
            onInput={(detail) => bloc.updateField('email', detail.value)}
            placeholder="Email address"
            label="Email address"
            icon={iconEnvelope}
            required
            disabled={bloc.isDisabled}
          />

          {#if bloc.errorMessage}
            <ErrorBanner message={bloc.errorMessage} />
          {/if}

          <button
            type="submit"
            class="btn-primary"
            class:loading={bloc.isSubmitting}
            disabled={bloc.isDisabled}
          >
            <span class="btn-label">{bloc.isSubmitting ? 'Sending…' : 'Send Reset Link'}</span>
            {#if bloc.isSubmitting}
              <span class="spinner" aria-hidden="true"></span>
            {/if}
          </button>
        </fieldset>
      </form>
    {/snippet}

    {#snippet footer()}
      Remembered it? <a href="/auth/login">Sign in</a>
    {/snippet}
  </AuthCard>
{/if}

<style>
  .glyph {
    width: 56px;
    height: 56px;
    border-radius: var(--weeb-radius-full);
    background: color-mix(in oklch, var(--weeb-accent) 16%, transparent);
    color: var(--weeb-accent-text);
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .glyph.good {
    background: color-mix(in oklch, var(--weeb-green) 15%, transparent);
    color: var(--weeb-green);
  }

  .lede {
    font-size: 14px;
    color: var(--weeb-fg-secondary);
    line-height: 1.5;
    text-align: center;
    margin: 0 0 8px;
  }

  .lede b {
    color: var(--weeb-fg);
    font-weight: 600;
    word-break: break-all;
  }

  .hint {
    font-size: 12.5px;
    color: var(--weeb-fg-muted);
    text-align: center;
    line-height: 1.5;
    margin: 0 0 20px;
  }

  .pr-form fieldset {
    display: flex;
    flex-direction: column;
    gap: 18px;
    border: none;
    padding: 0;
    margin: 0;
    min-width: 0;
  }

  .pr-form fieldset:disabled {
    opacity: 0.6;
  }

  .btn-primary {
    width: 100%;
    height: 46px;
    margin-top: 4px;
    background: var(--weeb-accent);
    color: white;
    font-size: 15px;
    font-weight: 600;
    letter-spacing: 0.01em;
    border: none;
    border-radius: var(--weeb-radius);
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 8px;
    transition: background 0.15s, transform 0.1s;
    position: relative;
    overflow: hidden;
  }

  .btn-primary:hover:not(:disabled) { background: var(--weeb-accent-hover); }
  .btn-primary:active:not(:disabled) { transform: scale(0.99); }
  .btn-primary:disabled { opacity: 0.5; cursor: not-allowed; }
  .btn-primary.loading .btn-label { opacity: 0; }

  .btn-ghost {
    width: 100%;
    height: 42px;
    background: var(--weeb-surface);
    color: var(--weeb-fg-secondary);
    font-size: 14px;
    font-weight: 500;
    font-family: inherit;
    border: 1px solid var(--weeb-border);
    border-radius: var(--weeb-radius);
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    text-decoration: none;
    transition: background 0.15s, color 0.15s;
  }

  .btn-ghost:hover {
    background: var(--weeb-surface-hover);
    color: var(--weeb-fg);
  }

  .spinner {
    display: block;
    position: absolute;
    width: 18px;
    height: 18px;
    border: 2px solid oklch(100% 0 0 / 0.3);
    border-top-color: white;
    border-radius: var(--weeb-radius-full);
    animation: spin 0.7s linear infinite;
  }

  @keyframes spin { to { transform: rotate(360deg); } }
  @media (prefers-reduced-motion: reduce) {
    .spinner { animation-duration: 2s; }
  }
</style>
