// src/views/auth/password-reset.tsx
import React, { useState, useEffect } from 'react';
import { useNavigate } from '../../utils/navigation';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {faLock, faArrowLeft, faCheckCircle, faUser, faEnvelope} from '@fortawesome/free-solid-svg-icons';
import Button, { ButtonColor, type StatusType } from '../../components/Button/Button';
import FormInput from '../../components/FormInput';
import { usePasswordReset } from '../../hooks/usePasswordReset';
import { type ResetPasswordInput } from '../../gql/graphql';

const PasswordReset: React.FC = () => {
  // Get search params manually since we're not using React Router
  const urlParams = new URLSearchParams(window.location.search);
  const navigate = useNavigate();
  const [token, setToken] = useState<string>('');
  const [email, setEmail] = useState<string>('');
  const [formData, setFormData] = useState({
    newPassword: '',
    confirmPassword: ''
  });
  const [errorMessage, setErrorMessage] = useState<string>('');
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [resetComplete, setResetComplete] = useState(false);

  const { mutate: mutateResetPassword, isLoading } = usePasswordReset(
    (response: boolean) => {
      if (response) {
        setResetComplete(true);
        setTimeout(() => {
          navigate('/');
        }, 3000);
      }
    },
    (error: any) => {
      setErrorMessage(error.message || 'Password reset failed. Please try again.');
    }
  );

  useEffect(() => {
    const tokenParam = urlParams.get('token');
    const emailParam = urlParams.get('email');

    if (!tokenParam) {
      setErrorMessage('Invalid or missing reset token. Please request a new password reset.');
      return;
    }

    if (!emailParam) {
      setErrorMessage('Invalid or missing email. Please request a new password reset.');
      return;
    }

    setToken(tokenParam);
    setEmail(emailParam);
  }, []);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
    // Clear error when user starts typing
    if (errorMessage) {
      setErrorMessage('');
    }
  };

  const validatePassword = () => {
    if (formData.newPassword.length < 8) {
      return 'Password must be at least 8 characters long';
    }
    if (formData.newPassword !== formData.confirmPassword) {
      return 'Passwords do not match';
    }
    return null;
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    const validationError = validatePassword();
    if (validationError) {
      setErrorMessage(validationError);
      return;
    }

    if (!token || !email) {
      setErrorMessage('Invalid reset token or email. Please request a new password reset.');
      return;
    }

    setErrorMessage('');
    mutateResetPassword({
      input: {
        token: token,
        newPassword: formData.newPassword,
        username: email
      }
    });
  };

  // Show error state if no token
  if (!token && !urlParams.get('token')) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-900 py-12 px-4 sm:px-6 lg:px-8">
        <div className="max-w-md w-full space-y-8">
          <div className="text-center">
            <div className="mx-auto h-12 w-12 bg-red-100 dark:bg-red-900 rounded-full flex items-center justify-center mb-4">
              <FontAwesomeIcon icon={faLock} className="text-red-600 dark:text-red-400 text-xl" />
            </div>
            <h2 className="text-3xl font-bold text-gray-900 dark:text-gray-100">
              Invalid Reset Link
            </h2>
            <p className="mt-4 text-gray-600 dark:text-gray-400">
              This password reset link is invalid or has expired.
            </p>
          </div>

          <div className="mt-8 space-y-4">
            <a
              href="/auth/password-reset-request"
              className="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md bg-blue-600 hover:bg-blue-700 text-white transition-colors"
            >
              Request New Reset Link
            </a>
            <a
              href="/"
              className="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100 transition-colors"
            >
              <FontAwesomeIcon icon={faArrowLeft} className="mr-2" />
              Back to Home
            </a>
          </div>
        </div>
      </div>
    );
  }

  // Show success state
  if (resetComplete) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-900 py-12 px-4 sm:px-6 lg:px-8">
        <div className="max-w-md w-full space-y-8">
          <div className="text-center">
            <div className="mx-auto h-12 w-12 bg-green-100 dark:bg-green-900 rounded-full flex items-center justify-center mb-4">
              <FontAwesomeIcon icon={faCheckCircle} className="text-green-600 dark:text-green-400 text-xl" />
            </div>
            <h2 className="text-3xl font-bold text-gray-900 dark:text-gray-100">
              Password Reset Complete
            </h2>
            <p className="mt-4 text-gray-600 dark:text-gray-400">
              Your password has been successfully reset. You can now log in with your new password.
            </p>
            <p className="mt-2 text-sm text-gray-500 dark:text-gray-500">
              Redirecting you to the home page...
            </p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-900 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-md w-full space-y-8">
        <div>
          <div className="mx-auto h-12 w-12 bg-blue-100 dark:bg-blue-900 rounded-full flex items-center justify-center">
            <FontAwesomeIcon icon={faLock} className="text-blue-600 dark:text-blue-400 text-xl" />
          </div>
          <h2 className="mt-6 text-center text-3xl font-bold text-gray-900 dark:text-gray-100">
            Set new password
          </h2>
          <p className="mt-2 text-center text-sm text-gray-600 dark:text-gray-400">
            Enter your new password below
          </p>
        </div>

        <form className="mt-8 space-y-6" onSubmit={handleSubmit}>
          <div className="space-y-4">
            <FormInput
              id="email"
              name="email"
              type="text"
              value={email}
              onChange={() => {}} // No-op since it's disabled
              placeholder="Email"
              label="Email"
              icon={faEnvelope}
              disabled={true}
            />

            <FormInput
              id="newPassword"
              name="newPassword"
              type="password"
              value={formData.newPassword}
              onChange={handleInputChange}
              placeholder="New password (min. 8 characters)"
              label="New Password"
              icon={faLock}
              required
              showPasswordToggle
              onPasswordToggle={() => setShowPassword(!showPassword)}
              isPasswordVisible={showPassword}
            />

            <FormInput
              id="confirmPassword"
              name="confirmPassword"
              type="password"
              value={formData.confirmPassword}
              onChange={handleInputChange}
              placeholder="Confirm new password"
              label="Confirm New Password"
              icon={faLock}
              required
              showPasswordToggle
              onPasswordToggle={() => setShowConfirmPassword(!showConfirmPassword)}
              isPasswordVisible={showConfirmPassword}
            />
          </div>

          {errorMessage && (
            <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-md p-3">
              <p className="text-sm text-red-600 dark:text-red-400">{errorMessage}</p>
            </div>
          )}

          <div className="text-xs text-gray-500 dark:text-gray-400">
            <p>Password requirements:</p>
            <ul className="list-disc list-inside mt-1 space-y-1">
              <li>At least 8 characters long</li>
              <li>Both passwords must match</li>
            </ul>
          </div>

          <div>
            <Button
              color={ButtonColor.blue}
              label="Reset Password"
              onClick={() => {}}
              showLabel
              status={isLoading ? 'loading' : 'idle'}
              className="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md"
            />
          </div>

          <div className="text-center">
            <a
              href="/"
              className="text-sm text-blue-600 dark:text-blue-400 hover:text-blue-500 dark:hover:text-blue-300 transition-colors"
            >
              ← Back to Home
            </a>
          </div>
        </form>
      </div>
    </div>
  );
};

export default PasswordReset;

// src/routes/auth/password-reset/+page.svelte
<script lang="ts">
  import Seo from '$lib/Seo.svelte';
  import { goto } from '$app/navigation';

  export let data;
  export let form;

  $: errorMessage = form?.errorMessage ?? data.errorMessage;
  $: successMessage = form?.successMessage ?? '';
  $: showForm = data.showForm && !successMessage;

  $: if (successMessage) {
    setTimeout(() => goto('/'), 3000);
  }
</script>

<Seo title="Reset Password" />

<div class="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-900 py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full space-y-8">
    {#if !showForm && !successMessage}
      <!-- Error state if no token -->
      <div class="text-center">
        <div class="mx-auto h-12 w-12 bg-red-100 dark:bg-red-900 rounded-full flex items-center justify-center mb-4">
          <svg class="text-red-600 dark:text-red-400 text-xl w-6 h-6" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clip-rule="evenodd" />
          </svg>
        </div>
        <h2 class="text-3xl font-bold text-gray-900 dark:text-gray-100">
          Invalid Reset Link
        </h2>
        <p class="mt-4 text-gray-600 dark:text-gray-400">
          This password reset link is invalid or has expired.
        </p>
      </div>

      <div class="mt-8 space-y-4">
        <a
          href="/auth/password-reset-request"
          class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md bg-blue-600 hover:bg-blue-700 text-white transition-colors"
        >
          Request New Reset Link
        </a>
        <a
          href="/"
          class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100 transition-colors"
        >
          ← Back to Home
        </a>
      </div>
    {/if}

    {#if successMessage}
      <!-- Success state -->
      <div class="text-center">
        <div class="mx-auto h-12 w-12 bg-green-100 dark:bg-green-900 rounded-full flex items-center justify-center mb-4">
          <svg class="text-green-600 dark:text-green-400 text-xl w-6 h-6" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
          </svg>
        </div>
        <h2 class="text-3xl font-bold text-gray-900 dark:text-gray-100">
          Password Reset Complete
        </h2>
        <p class="mt-4 text-gray-600 dark:text-gray-400">
          Your password has been successfully reset. You can now log in with your new password.
        </p>
        <p class="mt-2 text-sm text-gray-500 dark:text-gray-500">
          Redirecting you to the home page...
        </p>
      </div>
    {/if}

    {#if showForm}
      <!-- Main form -->
      <div>
        <div class="mx-auto h-12 w-12 bg-blue-100 dark:bg-blue-900 rounded-full flex items-center justify-center">
          <svg class="text-blue-600 dark:text-blue-400 text-xl w-6 h-6" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clip-rule="evenodd" />
          </svg>
        </div>
        <h2 class="mt-6 text-center text-3xl font-bold text-gray-900 dark:text-gray-100">
          Set new password
        </h2>
        <p class="mt-2 text-center text-sm text-gray-600 dark:text-gray-400">
          Enter your new password below
        </p>
      </div>

      <form class="mt-8 space-y-6" method="POST">
        <div class="space-y-4">
          <!-- Email field (disabled) -->
          <div>
            <label for="email" class="block text-sm font-medium mb-2 text-gray-700 dark:text-gray-300">
              Email
            </label>
            <div class="relative">
              <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                <svg class="h-5 w-5 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
                  <path d="M2.003 5.884L10 9.882l7.997-3.998A2 2 0 0016 4H4a2 2 0 00-1.997 1.884z" />
                  <path d="M18 8.118l-8 4-8-4V14a2 2 0 002 2h12a2 2 0 002-2V8.118z" />
                </svg>
              </div>
              <input
                id="email"
                name="email"
                type="text"
                value={data.email}
                disabled
                class="w-full px-4 py-3 pl-10 pr-4 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-400 transition-all duration-300 bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100 opacity-50 cursor-not-allowed border-gray-300 dark:border-gray-600"
                autocomplete="email"
              />
            </div>
          </div>

          <!-- New Password field -->
          <div>
            <label for="newPassword" class="block text-sm font-medium mb-2 text-gray-700 dark:text-gray-300">
              New Password
            </label>
            <div class="relative">
              <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                <svg class="h-5 w-5 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
                  <path fill-rule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clip-rule="evenodd" />
                </svg>
              </div>
              <input
                id="newPassword"
                name="newPassword"
                type="password"
                required
                placeholder="New password (min. 8 characters)"
                class="w-full px-4 py-3 pl-10 pr-4 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-400 transition-all duration-300 bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100 border-gray-300 dark:border-gray-600 focus:border-blue-400 dark:focus:border-blue-500"
                autocomplete="new-password"
              />
            </div>
          </div>

          <!-- Confirm Password field -->
          <div>
            <label for="confirmPassword" class="block text-sm font-medium mb-2 text-gray-700 dark:text-gray-300">
              Confirm New Password
            </label>
            <div class="relative">
              <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                <svg class="h-5 w-5 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
                  <path fill-rule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clip-rule="evenodd" />
                </svg>
              </div>
              <input
                id="confirmPassword"
                name="confirmPassword"
                type="password"
                required
                placeholder="Confirm new password"
                class="w-full px-4 py-3 pl-10 pr-4 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-400 transition-all duration-300 bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100 border-gray-300 dark:border-gray-600 focus:border-blue-400 dark:focus:border-blue-500"
                autocomplete="new-password"
              />
            </div>
          </div>
        </div>

        {#if errorMessage}
          <div class="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-md p-3">
            <p class="text-sm text-red-600 dark:text-red-400">{errorMessage}</p>
          </div>
        {/if}

        <div class="text-xs text-gray-500 dark:text-gray-400">
          <p>Password requirements:</p>
          <ul class="list-disc list-inside mt-1 space-y-1">
            <li>At least 8 characters long</li>
            <li>Both passwords must match</li>
          </ul>
        </div>

        <div>
          <button
            type="submit"
            class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 transition-colors"
          >
            Reset Password
          </button>
        </div>

        <div class="text-center">
          <a
            href="/"
            class="text-sm text-blue-600 dark:text-blue-400 hover:text-blue-500 dark:hover:text-blue-300 transition-colors"
          >
            ← Back to Home
          </a>
        </div>
      </form>
    {/if}
  </div>
</div>
