// src/lib/components/primitives/Button.svelte
<script lang="ts">
  import Fa from 'svelte-fa';
  import {
    faSpinner,
    faCheckCircle,
    faExclamationCircle,
  } from '@fortawesome/free-solid-svg-icons';

  type ButtonStatus = 'idle' | 'loading' | 'success' | 'error';

  let {
    color = 'blue',
    label = '',
    icon = '',
    onClick = () => {},
    showLabel = true,
    className = '',
    status = 'idle',
    onResetStatus,
    disabled = false,
  }: {
    color?: 'blue' | 'red' | 'transparent' | '';
    label?: string;
    /** Raw SVG markup rendered in place of the label. */
    icon?: string;
    onClick?: () => void;
    showLabel?: boolean;
    className?: string;
    status?: ButtonStatus;
    /** Called once the transient success/error state has been shown. */
    onResetStatus?: () => void;
    disabled?: boolean;
  } = $props();

  // The caller's status shows immediately, including on the first paint; success
  // and error are transient, so after two seconds the button falls back to idle
  // on its own. `expired` is that local override and nothing else.
  let expired = $state(false);
  const internalStatus = $derived<ButtonStatus>(expired ? 'idle' : status);

  $effect(() => {
    expired = false;
    if (status === 'idle') return;

    const timer = setTimeout(() => {
      expired = true;
      onResetStatus?.();
    }, 2000);
    return () => clearTimeout(timer);
  });

  const colorClasses = {
    blue: 'btn-accent',
    red: 'btn-danger',
    transparent: 'btn-ghost',
    '': '',
  };

  function handleClick() {
    if (internalStatus !== 'loading' && !disabled) {
      onClick();
    }
  }
</script>

<button
  onclick={handleClick}
  disabled={internalStatus === 'loading' || disabled}
  class="btn {colorClasses[color]} {className} {internalStatus === 'loading' ? 'cursor-not-allowed' : 'cursor-pointer'}"
>
  {#if internalStatus === 'loading'}
    <Fa icon={faSpinner} class="animate-spin" />
  {:else if internalStatus === 'success'}
    <Fa icon={faCheckCircle} class="text-green-500" />
  {:else if internalStatus === 'error'}
    <Fa icon={faExclamationCircle} class="text-red-500" />
  {:else}
    <!-- Idle state -->
    {#if icon}
      {@html icon}
    {:else if showLabel && label}
      <span>{label}</span>
    {/if}
  {/if}
</button>

<style>
  .btn {
    /* WCAG 2.5.5 at the shared base, so every variant clears it rather than
       each caller remembering to. */
    min-height: 44px;
    padding: 7px 18px;
    border-radius: var(--weeb-radius);
    /* Body step. 13px is not on the ramp, and it left the shared button a
       pixel adrift from the hero's own primary CTA at 14px. */
    font-size: 14px;
    font-weight: 600;
    font-family: inherit;
    transition: background 0.15s, color 0.15s, border-color 0.15s;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    white-space: nowrap;
    width: fit-content;
    position: relative;
    border: none;
    cursor: pointer;
  }
  .btn:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
  .btn-accent {
    background: var(--weeb-accent);
    color: white;
  }
  .btn-accent:hover:not(:disabled) {
    background: var(--weeb-accent-hover);
  }
  .btn-danger {
    background: var(--weeb-red);
    color: white;
  }
  .btn-danger:hover:not(:disabled) {
    filter: brightness(1.1);
  }
  .btn-ghost {
    background: transparent;
    color: var(--weeb-fg-secondary);
    border: 1px solid var(--weeb-border);
  }
  .btn-ghost:hover:not(:disabled) {
    color: var(--weeb-fg);
    background: var(--weeb-surface);
  }
</style>

// src/components/Button/Button.tsx
import React, { useEffect, useLayoutEffect, useRef, useState } from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faCheckCircle,
  faExclamationCircle,
  faSpinner,
} from "@fortawesome/free-solid-svg-icons";
import { motion, AnimatePresence } from "motion/react";

export enum ButtonColor {
  blue = "blue",
  red = "red",
  transparent = "transparent",
  none = "",
}

export type StatusType = "idle" | "loading" | "success" | "error";

interface StatusButtonProps {
  color: ButtonColor;
  label?: string;
  icon?: React.ReactNode;
  onClick: () => void;
  showLabel?: boolean;
  className?: string;
  status?: StatusType;
  onResetStatus?: () => void;
}

export default function StatusButton({
                                       color,
                                       label,
                                       icon,
                                       onClick,
                                       showLabel = true,
                                       className,
                                       status,
                                       onResetStatus,
                                     }: StatusButtonProps) {
  const [internalStatus, setInternalStatus] = useState<StatusType>("idle");
  const [buttonSize, setButtonSize] = useState<{ width: number; height: number } | null>(null);
  const buttonRef = useRef<HTMLButtonElement>(null);

  useLayoutEffect(() => {
    if (buttonRef.current && !buttonSize) {
      const { width, height } = buttonRef.current.getBoundingClientRect();
      setButtonSize({ width, height });
    }
  }, [buttonRef, buttonSize]);

  useEffect(() => {
    if (!status) return;
    setInternalStatus(status);
    if (status !== "idle") {
      const timeout = setTimeout(() => {
        setInternalStatus("idle");
        onResetStatus?.();
      }, 2000);
      return () => clearTimeout(timeout);
    }
  }, [status, onResetStatus]);

  const colorClasses = {
    blue: "bg-blue-600 hover:bg-blue-700 text-white",
    red: "bg-red-600 hover:bg-red-700 text-white",
    transparent:
      "bg-transparent hover:bg-gray-100 text-gray-700 border border-gray-300",
    none: "",
  };

  const iconMap: Record<StatusType, React.ReactNode> = {
    loading: <FontAwesomeIcon icon={faSpinner} spin />,
    success: <FontAwesomeIcon icon={faCheckCircle} className="text-green-500" />,
    error: <FontAwesomeIcon icon={faExclamationCircle} className="text-red-500" />,
    idle: null,
  };

  return (
    <button
      ref={buttonRef}
      onClick={onClick}
      disabled={internalStatus === "loading"}
      className={`
      px-4 py-1
        relative rounded-full font-medium transition flex items-center justify-center whitespace-nowrap
        ${colorClasses[color]} ${className || ""} ${
        internalStatus === "loading" ? "cursor-not-allowed" : "cursor-pointer"
      }`}
      style={
        buttonSize
          ? { width: `${buttonSize.width}px`, height: `${buttonSize.height}px` }
          : undefined
      }
    >
      <AnimatePresence mode="wait" initial={false}>
        {internalStatus === "idle" ? (
          <motion.div
            key="button"
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.9 }}
            transition={{ duration: 0.2 }}
            className="flex items-center"
          >
            {icon ? icon : showLabel && label && <span>{label}</span>}
          </motion.div>
        ) : (
          <motion.div
            key={internalStatus}
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.9 }}
            transition={{ duration: 0.2 }}
            className="flex items-center"
          >
            {iconMap[internalStatus]}
          </motion.div>
        )}
      </AnimatePresence>
    </button>
  );
}

export type { StatusButtonProps as ButtonProps };
