// src/components/Toast/Toast.tsx
import React, { useEffect, useState } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faX, faClock, faPlay } from '@fortawesome/free-solid-svg-icons';
import { GetImageFromAnime } from '../../services/utils';
import {SafeImage} from "../SafeImage/SafeImage";
import { useNavigate } from '../../utils/navigation';

export interface ToastProps {
  id: string;
  type: 'warning' | 'info' | 'success';
  title: string;
  message: string;
  duration?: number;
  onClose: (id: string) => void;
  anime?: {
    id: string;
    titleEn?: string | null;
    titleJp?: string | null;
    imageUrl?: string | null;
  };
}

const Toast: React.FC<ToastProps> = ({
  id,
  type,
  title,
  message,
  duration = 6000,
  onClose,
  anime
}) => {
  const navigate = useNavigate();
  const [isVisible, setIsVisible] = useState(true);
  const [progress, setProgress] = useState(100);

  useEffect(() => {
    const startTime = Date.now();
    const updateProgress = () => {
      const elapsed = Date.now() - startTime;
      const remaining = Math.max(0, (duration - elapsed) / duration * 100);
      setProgress(remaining);

      if (remaining > 0) {
        requestAnimationFrame(updateProgress);
      } else {
        setIsVisible(false);
        setTimeout(() => onClose(id), 300); // Wait for exit animation
      }
    };

    const animationFrame = requestAnimationFrame(updateProgress);
    return () => cancelAnimationFrame(animationFrame);
  }, [id, duration, onClose]);

  const handleClose = (e: React.MouseEvent) => {
    e.stopPropagation(); // Prevent navigation when clicking close button
    setIsVisible(false);
    setTimeout(() => onClose(id), 300);
  };

  const handleToastClick = () => {
    if (anime) {
      navigate(`/show/${anime.id}`);
    }
  };

  const getIcon = () => {
    switch (type) {
      case 'warning':
        return <FontAwesomeIcon icon={faClock} className="w-5 h-5" />;
      case 'info':
        return <FontAwesomeIcon icon={faPlay} className="w-5 h-5" />;
      case 'success':
        return <FontAwesomeIcon icon={faPlay} className="w-5 h-5" />;
      default:
        return null;
    }
  };

  const getColorClasses = () => {
    switch (type) {
      case 'warning':
        return {
          container: 'bg-white/90 dark:bg-black/60 backdrop-blur-sm border border-gray-200 dark:border-gray-700',
          icon: 'text-yellow-500',
          title: 'text-gray-900 dark:text-white',
          message: 'text-gray-600 dark:text-gray-200',
          close: 'text-gray-400 hover:text-gray-600 dark:hover:text-gray-200'
        };
      case 'info':
        return {
          container: 'bg-white/90 dark:bg-black/60 backdrop-blur-sm border border-gray-200 dark:border-gray-700',
          icon: 'text-blue-500',
          title: 'text-gray-900 dark:text-white',
          message: 'text-gray-600 dark:text-gray-200',
          close: 'text-gray-400 hover:text-gray-600 dark:hover:text-gray-200'
        };
      case 'success':
        return {
          container: 'bg-white/90 dark:bg-black/60 backdrop-blur-sm border border-gray-200 dark:border-gray-700',
          icon: 'text-green-500',
          title: 'text-gray-900 dark:text-white',
          message: 'text-gray-600 dark:text-gray-200',
          close: 'text-gray-400 hover:text-gray-600 dark:hover:text-gray-200'
        };
    }
  };

  const colors = getColorClasses();

  return (
    <div
      className={`
        transform transition-all duration-500 ease-out mb-3 max-w-xs w-full
        ${isVisible 
          ? 'translate-x-0 opacity-100 scale-100' 
          : 'translate-x-full opacity-0 scale-95'
        }
      `}
    >
      <div 
        className={`
          ${colors.container} 
          rounded-lg shadow-md overflow-hidden
          transition-all duration-300
          ${anime ? 'cursor-pointer hover:scale-105' : ''}
        `}
        onClick={anime ? handleToastClick : undefined}
      >
        <div className="p-3">
          {/* Top Title */}
          <div className="flex items-center justify-between mb-2">
            <div className="flex items-center gap-1.5">
              <div className={`flex-shrink-0 ${colors.icon} flex items-center`}>
                {getIcon()}
              </div>
              <p className={`text-xs font-semibold ${colors.title} uppercase tracking-wide flex items-center`}>
                {title}
              </p>
            </div>
            <button
              onClick={handleClose}
              className={`
                flex-shrink-0 p-1 rounded-full transition-all duration-200
                ${colors.close} hover:bg-gray-100 dark:hover:bg-gray-700/50
                hover:scale-110 active:scale-95
              `}
            >
              <FontAwesomeIcon icon={faX} className="w-2.5 h-2.5" />
            </button>
          </div>

          {/* Content with Image and Text */}
          <div className="flex items-center gap-3">
            {/* Poster Image */}
            {anime && (
              <div className="flex-shrink-0">
                <SafeImage
                  src={GetImageFromAnime(anime)}
                  alt={anime.titleEn || anime.titleJp || 'Anime Poster'}
                  className="w-12 h-16 rounded-lg object-cover border border-white/20 dark:border-white/10"
                  onError={({currentTarget}) => {
                    currentTarget.onerror = null; // prevents looping
                    currentTarget.src = "/assets/not found.jpg";
                  }}
                />
              </div>
            )}

            {/* Text Content */}
            <div className="flex-1 min-w-0">
              {/* Anime Title */}
              {anime && (
                <p className={`text-sm font-bold ${colors.title} truncate mb-0.5`}>
                  {anime.titleEn || anime.titleJp}
                </p>
              )}

              {/* Episode Info */}
              <p className={`text-xs ${colors.message} truncate`}>
                {message}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Toast;

// src/svelte/components/Toast.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { fade, fly } from 'svelte/transition';
  import { navigateWithTransition } from '../../utils/astro-navigation';
  import { GetImageFromAnime } from '../../services/utils';
  import SafeImage from './SafeImage.svelte';
  import type { ToastData } from '../stores/toast';
  import '@fortawesome/fontawesome-free/css/all.min.css';

  export let toast: ToastData;
  export let onClose: (id: string) => void;

  let isVisible = true;
  let progress = 100;
  let progressInterval: NodeJS.Timeout;

  $: typeStyles = {
    warning: 'bg-orange-500 border-orange-600',
    info: 'bg-blue-500 border-blue-600',
    success: 'bg-green-500 border-green-600'
  };

  $: iconClass = {
    warning: 'fa-exclamation-triangle',
    info: 'fa-info-circle',
    success: 'fa-check-circle'
  };

  onMount(() => {
    const startTime = Date.now();
    const updateProgress = () => {
      const elapsed = Date.now() - startTime;
      const remaining = Math.max(0, (toast.duration! - elapsed) / toast.duration! * 100);
      progress = remaining;

      if (remaining > 0) {
        progressInterval = setTimeout(updateProgress, 16); // ~60fps
      } else {
        handleClose();
      }
    };

    progressInterval = setTimeout(updateProgress, 16);
  });

  onDestroy(() => {
    if (progressInterval) {
      clearTimeout(progressInterval);
    }
  });

  function handleClose() {
    isVisible = false;
    setTimeout(() => onClose(toast.id), 300); // Wait for exit animation
  }

  function handleAnimeClick() {
    if (toast.anime?.id) {
      navigateWithTransition(`/show/${toast.anime.id}`);
      handleClose();
    }
  }
</script>

{#if isVisible}
  <div
    class="toast-container mb-3 max-w-sm w-full bg-white dark:bg-gray-800 shadow-lg rounded-lg pointer-events-auto ring-1 ring-black ring-opacity-5 dark:ring-gray-600 overflow-hidden"
    in:fly={{ x: 300, duration: 300 }}
    out:fly={{ x: 300, duration: 300 }}
  >
    <!-- Progress bar -->
    <div class="absolute top-0 left-0 h-1 bg-gray-200 dark:bg-gray-700 w-full">
      <div
        class="h-full transition-all duration-75 ease-linear {typeStyles[toast.type]}"
        style="width: {progress}%"
      ></div>
    </div>

    <div class="p-4">
      <div class="flex items-start">
        <!-- Icon -->
        <div class="flex-shrink-0">
          <i class="fas {iconClass[toast.type]} text-lg {toast.type === 'warning' ? 'text-orange-500' : toast.type === 'info' ? 'text-blue-500' : 'text-green-500'}"></i>
        </div>

        <!-- Content -->
        <div class="ml-3 w-0 flex-1">
          <p class="text-sm font-medium text-gray-900 dark:text-gray-100">
            {toast.title}
          </p>
          <p class="mt-1 text-sm text-gray-500 dark:text-gray-400">
            {toast.message}
          </p>

          <!-- Anime info if present -->
          {#if toast.anime}
            <div
              class="mt-3 flex items-center space-x-3 cursor-pointer hover:bg-gray-50 dark:hover:bg-gray-700 p-2 rounded-md transition-colors"
              on:click={handleAnimeClick}
              on:keydown={(e) => e.key === 'Enter' && handleAnimeClick()}
              role="button"
              tabindex="0"
            >
              <div class="flex-shrink-0">
                <SafeImage
                  src={GetImageFromAnime(toast.anime)}
                  alt={toast.anime.titleEn || toast.anime.titleJp || 'Anime'}
                  className="w-8 h-8 rounded object-cover"
                  fallbackClassName="w-8 h-8 rounded bg-gray-300 dark:bg-gray-600 flex items-center justify-center"
                />
              </div>
              <div class="flex-1 min-w-0">
                <p class="text-sm font-medium text-gray-900 dark:text-gray-100 truncate">
                  {toast.anime.titleEn || toast.anime.titleJp}
                </p>
                <div class="flex items-center text-xs text-gray-500 dark:text-gray-400">
                  <i class="fas fa-play mr-1"></i>
                  View Details
                </div>
              </div>
            </div>
          {/if}
        </div>

        <!-- Close button -->
        <div class="ml-4 flex-shrink-0 flex">
          <button
            class="bg-white dark:bg-gray-800 rounded-md inline-flex text-gray-400 hover:text-gray-500 dark:hover:text-gray-300 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
            on:click={handleClose}
          >
            <span class="sr-only">Close</span>
            <i class="fas fa-times text-sm"></i>
          </button>
        </div>
      </div>
    </div>
  </div>
{/if}

<style>
  .toast-container {
    transition: all 0.3s ease-in-out;
  }
</style>
