// src/svelte/components/MobileToast.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { slide } from 'svelte/transition';
  import { navigateWithTransition } from '../../utils/astro-navigation';
  import { GetImageFromAnime } from '../../services/utils';
  import SafeImage from './SafeImage.svelte';
  import type { ToastData } from '../stores/toast';
  import '@fortawesome/fontawesome-free/css/all.min.css';

  export let toast: ToastData;
  export let onClose: (id: string) => void;

  let isVisible = true;
  let progress = 100;
  let progressInterval: NodeJS.Timeout;

  $: typeStyles = {
    warning: 'bg-orange-500',
    info: 'bg-blue-500',
    success: 'bg-green-500'
  };

  $: iconClass = {
    warning: 'fa-exclamation-triangle',
    info: 'fa-info-circle',
    success: 'fa-check-circle'
  };

  onMount(() => {
    const startTime = Date.now();
    const updateProgress = () => {
      const elapsed = Date.now() - startTime;
      const remaining = Math.max(0, (toast.duration! - elapsed) / toast.duration! * 100);
      progress = remaining;

      if (remaining > 0) {
        progressInterval = setTimeout(updateProgress, 16); // ~60fps
      } else {
        handleClose();
      }
    };

    progressInterval = setTimeout(updateProgress, 16);
  });

  onDestroy(() => {
    if (progressInterval) {
      clearTimeout(progressInterval);
    }
  });

  function handleClose() {
    isVisible = false;
    setTimeout(() => onClose(toast.id), 300); // Wait for exit animation
  }

  function handleAnimeClick() {
    if (toast.anime?.id) {
      navigateWithTransition(`/show/${toast.anime.id}`);
      handleClose();
    }
  }
</script>

{#if isVisible}
  <div
    class="fixed top-20 left-4 right-4 z-50 bg-white dark:bg-gray-800 shadow-lg rounded-lg ring-1 ring-black ring-opacity-5 dark:ring-gray-600 overflow-hidden"
    in:slide={{ duration: 300 }}
    out:slide={{ duration: 300 }}
  >
    <!-- Progress bar -->
    <div class="absolute top-0 left-0 h-1 bg-gray-200 dark:bg-gray-700 w-full">
      <div
        class="h-full transition-all duration-75 ease-linear {typeStyles[toast.type]}"
        style="width: {progress}%"
      ></div>
    </div>

    <div class="p-4">
      <div class="flex items-start">
        <!-- Icon -->
        <div class="flex-shrink-0">
          <i class="fas {iconClass[toast.type]} text-lg {toast.type === 'warning' ? 'text-orange-500' : toast.type === 'info' ? 'text-blue-500' : 'text-green-500'}"></i>
        </div>

        <!-- Content -->
        <div class="ml-3 flex-1 min-w-0">
          <p class="text-sm font-medium text-gray-900 dark:text-gray-100">
            {toast.title}
          </p>
          <p class="mt-1 text-sm text-gray-500 dark:text-gray-400">
            {toast.message}
          </p>

          <!-- Anime info if present -->
          {#if toast.anime}
            <div
              class="mt-3 flex items-center space-x-3 cursor-pointer hover:bg-gray-50 dark:hover:bg-gray-700 p-2 rounded-md transition-colors"
              on:click={handleAnimeClick}
              on:keydown={(e) => e.key === 'Enter' && handleAnimeClick()}
              role="button"
              tabindex="0"
            >
              <div class="flex-shrink-0">
                <SafeImage
                  src={GetImageFromAnime(toast.anime)}
                  alt={toast.anime.titleEn || toast.anime.titleJp || 'Anime'}
                  className="w-8 h-8 rounded object-cover"
                  fallbackClassName="w-8 h-8 rounded bg-gray-300 dark:bg-gray-600 flex items-center justify-center"
                />
              </div>
              <div class="flex-1 min-w-0">
                <p class="text-sm font-medium text-gray-900 dark:text-gray-100 truncate">
                  {toast.anime.titleEn || toast.anime.titleJp}
                </p>
                <div class="flex items-center text-xs text-gray-500 dark:text-gray-400">
                  <i class="fas fa-play mr-1"></i>
                  View Details
                </div>
              </div>
            </div>
          {/if}
        </div>

        <!-- Close button -->
        <div class="ml-4 flex-shrink-0">
          <button
            class="bg-white dark:bg-gray-800 rounded-md inline-flex text-gray-400 hover:text-gray-500 dark:hover:text-gray-300 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
            on:click={handleClose}
          >
            <span class="sr-only">Close</span>
            <i class="fas fa-times text-sm"></i>
          </button>
        </div>
      </div>
    </div>
  </div>
{/if}

// src/components/Toast/MobileToast.tsx
import React, { useEffect, useState } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faX, faClock, faPlay } from '@fortawesome/free-solid-svg-icons';
import { GetImageFromAnime } from '../../services/utils';
import { SafeImage } from "../SafeImage/SafeImage";
import { useNavigate } from '../../utils/navigation';
import type { ToastProps } from './Toast';

const MobileToast: React.FC<ToastProps> = ({
  id,
  type,
  title,
  message,
  duration = 6000,
  onClose,
  anime
}) => {
  const navigate = useNavigate();
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    // Slide in animation
    setTimeout(() => setIsVisible(true), 50);

    // Auto-hide after duration
    const timeout = setTimeout(() => {
      setIsVisible(false);
      setTimeout(() => onClose(id), 300);
    }, duration);

    return () => clearTimeout(timeout);
  }, [id, duration, onClose]);

  const handleClose = (e: React.MouseEvent) => {
    e.stopPropagation();
    setIsVisible(false);
    setTimeout(() => onClose(id), 300);
  };

  const handleToastClick = () => {
    if (anime) {
      navigate(`/show/${anime.id}`);
    }
  };

  const getIcon = () => {
    switch (type) {
      case 'warning':
        return <FontAwesomeIcon icon={faClock} className="w-4 h-4" />;
      case 'info':
        return <FontAwesomeIcon icon={faPlay} className="w-4 h-4" />;
      case 'success':
        return <FontAwesomeIcon icon={faPlay} className="w-4 h-4" />;
      default:
        return null;
    }
  };

  const getColorClasses = () => {
    switch (type) {
      case 'warning':
        return {
          container: 'bg-white/90 dark:bg-black/60 backdrop-blur-sm border-b border-gray-200 dark:border-gray-700',
          icon: 'text-yellow-500',
          title: 'text-gray-900 dark:text-white',
          message: 'text-gray-600 dark:text-gray-200',
          close: 'text-gray-400 hover:text-gray-600 dark:hover:text-gray-200'
        };
      case 'info':
        return {
          container: 'bg-white/90 dark:bg-black/60 backdrop-blur-sm border-b border-gray-200 dark:border-gray-700',
          icon: 'text-blue-500',
          title: 'text-gray-900 dark:text-white',
          message: 'text-gray-600 dark:text-gray-200',
          close: 'text-gray-400 hover:text-gray-600 dark:hover:text-gray-200'
        };
      case 'success':
        return {
          container: 'bg-white/90 dark:bg-black/60 backdrop-blur-sm border-b border-gray-200 dark:border-gray-700',
          icon: 'text-green-500',
          title: 'text-gray-900 dark:text-white',
          message: 'text-gray-600 dark:text-gray-200',
          close: 'text-gray-400 hover:text-gray-600 dark:hover:text-gray-200'
        };
    }
  };

  const colors = getColorClasses();

  return (
    <div
      className={`
        fixed top-0 left-0 right-0 z-30 transition-all duration-300 ease-out
        ${isVisible ? 'translate-y-[5.5rem]' : '-translate-y-full opacity-0'}
        ${anime ? 'cursor-pointer' : ''}
      `}
      onClick={anime ? handleToastClick : undefined}
    >
      {/* Background with blur - similar to sticky header */}
      <div className="relative overflow-hidden">
        {/* Background image if anime has one */}
        {anime && (
          <div
            className="absolute inset-0 bg-cover bg-center opacity-20"
            style={{
              backgroundImage: `url(${global.config.cdn_url}/${GetImageFromAnime(anime)})`,
              filter: 'blur(8px)',
              transform: 'scale(1.1)',
            }}
          />
        )}

        {/* Overlay */}
        <div className={`absolute inset-0 ${colors.container}`} />

        {/* Content */}
        <div className="max-w-screen-2xl mx-auto relative z-10 px-4 py-3">
          <div className="flex items-center gap-3">
            {/* Poster Image */}
            {anime && (
              <div className="flex-shrink-0">
                <SafeImage
                  src={GetImageFromAnime(anime)}
                  alt={anime.titleEn || anime.titleJp || 'Anime Poster'}
                  className="w-8 h-12 rounded object-cover border border-white/20 dark:border-white/10"
                  onError={({currentTarget}) => {
                    currentTarget.onerror = null;
                    currentTarget.src = "/assets/not found.jpg";
                  }}
                />
              </div>
            )}

            {/* Content */}
            <div className="min-w-0 flex-1">
              {/* Notification Title */}
              <div className="flex items-center gap-1.5 mb-0.5">
                <div className={`flex-shrink-0 ${colors.icon} flex items-center`}>
                  {getIcon()}
                </div>
                <p className={`text-xs font-semibold ${colors.title} uppercase tracking-wide`}>
                  {title}
                </p>
              </div>

              {/* Anime Title */}
              {anime && (
                <h1 className={`text-sm font-bold ${colors.title} truncate mb-0.5`}>
                  {anime.titleEn || anime.titleJp}
                </h1>
              )}

              {/* Episode Info */}
              <p className={`text-xs ${colors.message} truncate`}>
                {message}
              </p>
            </div>

            {/* Close Button */}
            <button
              onClick={handleClose}
              className={`
                flex-shrink-0 p-2 rounded-full transition-all duration-200
                ${colors.close} hover:bg-gray-100 dark:hover:bg-gray-700/50
                hover:scale-110 active:scale-95
              `}
            >
              <FontAwesomeIcon icon={faX} className="w-3 h-3" />
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default MobileToast;
