// src/components/AnimeCard/AnimeCard.tsx
import Card from "../Card";
import {FontAwesomeIcon} from "@fortawesome/react-fontawesome";
import {faCalendar, faClapperboard, faClock} from "@fortawesome/free-solid-svg-icons";
import Button, {ButtonColor} from "../Button";
import {Skeleton} from "../Skeleton/Skeleton";
import {SafeImage} from "../SafeImage/SafeImage";
import {Link} from "react-router-dom";
import {getAirTimeDisplay} from "../../services/airTimeUtils";
import {useAnimeCountdowns} from "../../hooks/useAnimeCountdowns";

enum AnimeCardStyle {
  DEFAULT = 'default',
  HOVER_TRANSPARENT = 'hover-transparent',
  HOVER = 'hover',

  TRANSPARENT = 'transparent',
  LONG = 'long',
  DETAIL = 'detail',
  EPISODE = 'episode',

}

interface AnimeCardProps {
  style: AnimeCardStyle
  forceListLayout?: boolean
  title: string
  description: string
  episodes: number
  episodeLength: string
  year: string
  image: string
  onClick: () => void
  className?: string
  options: React.ReactNode[]
  id: string | null | undefined
  airTime?: {
    show: boolean
    text: string
    variant?: 'countdown' | 'scheduled' | 'aired' | 'airing'
    icon?: React.ReactNode
  }
  // For automatic air time calculation
  nextEpisode?: {
    airDate?: string | null
  } | null
  broadcast?: string | null
}

interface AnimeEpisodeCardProps {
  style: AnimeCardStyle
  title: string
  description: string
  episodes: string
  episodeLength: string
  year: string
  airdate: string
  episodeTitle: string
  episodeNumber: string
  image: string
  onClick: () => void
  className?: string
  airTime?: {
    show: boolean
    text: string
    variant?: 'countdown' | 'scheduled' | 'aired' | 'airing'
    icon?: React.ReactNode
  }
}

const cardStyles = {
  default: `w-48 h-72`,
  'hover-transparent': `w-48 h-72 hover:bg-gray-100 dark:hover:bg-gray-700`,
  hover: `w-48 h-72 hover:bg-gray-100 dark:hover:bg-gray-700 hover:shadow-lg`,
  transparent: `w-48 h-72 bg-transparent`,
  long: `w-96 h-96`,
  detail: ``,
  episode: ``,
}

function AnimeCard(props: AnimeCardProps | AnimeEpisodeCardProps) {
  const { getCountdown } = useAnimeCountdowns();
  
  // Get real-time countdown from web worker if available
  const workerCountdown = (props as AnimeCardProps).id ? getCountdown((props as AnimeCardProps).id!) : null;
  
  // Calculate air time display
  let displayAirTime = (props as AnimeCardProps).airTime;
  
  if (!displayAirTime && (props as AnimeCardProps).nextEpisode?.airDate && (props as AnimeCardProps).broadcast) {
    // Use worker countdown if available, otherwise fallback to static calculation
    if (workerCountdown) {
      displayAirTime = {
        show: true,
        text: workerCountdown.isAiring 
          ? `Currently airing (${workerCountdown.countdown})` 
          : workerCountdown.hasAired 
            ? "Recently aired"
            : workerCountdown.countdown.includes("m") || workerCountdown.countdown.includes("h")
              ? `Airing in ${workerCountdown.countdown}`
              : workerCountdown.countdown,
        variant: workerCountdown.isAiring 
          ? 'airing' as const
          : workerCountdown.hasAired 
            ? 'aired' as const 
            : 'countdown' as const,
      };
    } else {
      // Fallback to static calculation
      displayAirTime = getAirTimeDisplay((props as AnimeCardProps).nextEpisode?.airDate, (props as AnimeCardProps).broadcast) || undefined;
    }
  }

  return (
    <Card
      className={`flex ${(props as AnimeCardProps).forceListLayout ? "flex-row" : "sm:flex-row md:flex-col"} bg-white dark:bg-gray-800 rounded-md shadow-sm w-full justify-center transition-colors duration-300 ${props.className || ''}`}
    >

      <Link to={`/show/${(props as AnimeCardProps).id}`}
            className={`flex flex-col flex-none bg-white dark:bg-gray-800 ${cardStyles[props.style]} flex-grow overflow-hidden transition-colors duration-300 ${(props as AnimeCardProps).forceListLayout ? "rounded-l-md" : "rounded-l-md lg:rounded-bl-none lg:rounded-t-md"} `}>
        <SafeImage
          src={props.image}
          alt={props.title}
          data-original-src={props.image}
          className={`aspect-2/3 object-cover flex-auto relative
          
        ${
            (props as AnimeCardProps).forceListLayout ? "w-24 sm:w-28 md:w-32" : "w-32 sm:w-40 md:w-48  "
          }`}
          onError={({currentTarget}) => {
            currentTarget.onerror = null; // prevents looping
            currentTarget.src = "/assets/not found.jpg";
          }}
        />
      </Link>
      {props.style === AnimeCardStyle.DETAIL && (
        <div
          className={`flex flex-col flex-grow min-w-0 sm:justify-start sm:align-left p-4 sm:w-full lg:w-full space-y-4 h-full relative w-full group`}
        >


          <Link to={`/show/${(props as AnimeCardProps).id}`} className={"flex overflow-hidden flex-col w-full"}>
            <div className="group w-full">
              {/* Default (visible) */}
              <span className="block whitespace-nowrap text-md font-bold w-full truncate group-hover:hidden text-gray-900 dark:text-gray-100">
    {props.title}
  </span>

              {/* On hover (revealed) */}
              <span
                className="hidden group-hover:block whitespace-nowrap w-max text-md font-bold group-hover:animate-marquee text-gray-900 dark:text-gray-100">
    {props.title}
  </span>
            </div>
            <div className="flex flex-col space-y-2 text-md font-normal mt-2 items-start text-gray-700 dark:text-gray-300">
              <div className="flex items-center gap-2">
                <FontAwesomeIcon icon={faClapperboard}/>
                <span>{props.episodes}</span>
              </div>
              <div className="flex items-center gap-2">
                <FontAwesomeIcon icon={faClock}/>
                <span>{props.episodeLength}</span>
              </div>
              <div className="flex items-center gap-2">
                <FontAwesomeIcon icon={faCalendar}/>
                <span>{props.year}</span>
              </div>
              {displayAirTime?.show && (
                <div className={`flex items-center gap-2 ${
                  displayAirTime?.variant === 'countdown' ? 'text-red-600 dark:text-red-400' :
                  displayAirTime?.variant === 'airing' ? 'text-orange-600 dark:text-orange-400' :
                  displayAirTime?.variant === 'aired' ? 'text-green-600 dark:text-green-400' :
                  'text-blue-600 dark:text-blue-400'
                }`}>
                  {displayAirTime?.icon || <FontAwesomeIcon icon={faCalendar}/>}
                  <span className="text-xs font-medium">{displayAirTime?.text}</span>
                </div>
              )}
            </div>
          </Link>
          <div
            className={`flex flex-wrap gap-2 options w-full ${
              (props as AnimeCardProps).forceListLayout ? 'justify-start' : 'justify-center'
            }`}
          >
            {(props as AnimeCardProps).options?.length > 0 &&
              (props as AnimeCardProps).options.map((option, index) => (
                <div key={index} className="flex items-center">
                  {option}
                </div>
              ))}
          </div>


        </div>
      )}
      {props.style === AnimeCardStyle.EPISODE && (
        <div
          className={`flex flex-col flex-grow min-w-0 sm:justify-start sm:align-left p-4 sm:w-full lg:w-full space-y-4 h-full relative w-full  group`}
        >

          <Link to={`/show/${(props as AnimeCardProps).id}`} className={"flex flex-col overflow-hidden w-full"}>
            <div className="group w-full">
              {/* Default (visible) */}
              <span className="block whitespace-nowrap text-md font-bold w-full truncate group-hover:hidden text-gray-900 dark:text-gray-100">
    {props.title}
  </span>

              {/* On hover (revealed) */}
              <span
                className="hidden group-hover:block whitespace-nowrap text-md font-bold group-hover:animate-marquee">
    {props.title}
  </span>
            </div>
            <div className="group w-full">
              {/* Default (visible) */}
              <span className="block whitespace-nowrap text-md font-normal w-full truncate group-hover:hidden text-gray-900 dark:text-gray-100">
    {(props as AnimeEpisodeCardProps).episodeTitle}
  </span>

              {/* On hover (revealed) */}
              <span
                className="hidden group-hover:block whitespace-nowrap text-md font-normal group-hover:animate-marquee text-gray-900 dark:text-gray-100">
    {(props as AnimeEpisodeCardProps).episodeTitle}
  </span>
            </div>
            <div className={`flex flex-col w-full justify-between space-y-2`}>
              <span
                className={`flex-grow text-md text-base space-x-4 text-gray-600 dark:text-gray-400`}><span>{`episode ${(props as AnimeEpisodeCardProps).episodeNumber}`}</span></span>
              
              {/* Configurable air time display or fallback to airdate */}
              {(props as AnimeEpisodeCardProps).airTime?.show ? (
                <div className={`flex items-center gap-2 ${
                  (props as AnimeEpisodeCardProps).airTime?.variant === 'countdown' ? 'text-red-600 dark:text-red-400' :
                  (props as AnimeEpisodeCardProps).airTime?.variant === 'airing' ? 'text-orange-600 dark:text-orange-400' :
                  (props as AnimeEpisodeCardProps).airTime?.variant === 'aired' ? 'text-green-600 dark:text-green-400' :
                  'text-blue-600 dark:text-blue-400'
                }`}>
                  {(props as AnimeEpisodeCardProps).airTime?.icon || <FontAwesomeIcon icon={faCalendar}/>}
                  <span className="text-xs font-medium">{(props as AnimeEpisodeCardProps).airTime?.text}</span>
                </div>
              ) : (
                <span
                  className={`flex-grow text-md text-base space-x-4 text-gray-600 dark:text-gray-400`}><span>{(props as AnimeEpisodeCardProps).airdate}</span></span>
              )}
            </div>
          </Link>
          {/* if list align left */}
          <div
            className={`flex flex-wrap gap-2 options w-full ${
              (props as AnimeCardProps).forceListLayout ? 'justify-start' : 'justify-center'
            }`}
          >
            {(props as AnimeCardProps).options?.length > 0 &&
              (props as AnimeCardProps).options.map((option, index) => (
                <div key={index} className="flex items-center">
                  {option}
                </div>
              ))}
          </div>

        </div>
      )}
    </Card>
  )
}

export {AnimeCard as default, AnimeCardStyle}

export type {AnimeCardProps}


interface SkeletonProps {
  style: AnimeCardStyle;
  forceListLayout?: boolean;
}

export function AnimeCardSkeleton({style, forceListLayout = false}: SkeletonProps) {
  const isEpisode = style === AnimeCardStyle.EPISODE;

  return (
    <div
      className={`flex ${forceListLayout ? "flex-row" : "sm:flex-row md:flex-col"} 
        bg-white dark:bg-gray-800 rounded-md shadow-sm w-full transition-colors duration-300 
        ${isEpisode ? "w-24 sm:w-28 md:w-32" : "w-32 sm:w-40 md:w-44"} 
        overflow-hidden animate-pulse`}
    >

      <div
        className={`aspect-2/3 bg-gray-200 dark:bg-gray-700 ${
          forceListLayout ? "w-24 sm:w-28 md:w-32" : "w-32 sm:w-40 md:w-44"
        }`}
      />
      <div className="flex flex-col justify-between px-4 py-3 w-full h-full">
        <div className="space-y-2">
          <div className="w-full h-4 bg-gray-200 dark:bg-gray-700 rounded"/>
          {isEpisode ? (
            <>
              <div className="w-2/3 h-3 bg-gray-200 dark:bg-gray-700 rounded"/>
              <div className="w-1/2 h-3 bg-gray-200 dark:bg-gray-700 rounded"/>
              <div className="w-2/3 h-3 bg-gray-200 dark:bg-gray-700 rounded"/>
            </>
          ) : (
            <>
              <div className="w-2/3 h-3 bg-gray-200 dark:bg-gray-700 rounded"/>
              <div className="w-1/3 h-3 bg-gray-200 dark:bg-gray-700 rounded"/>
              <div className="w-1/4 h-3 bg-gray-200 dark:bg-gray-700 rounded"/>
            </>
          )}
        </div>
        <div className="pt-3">
          <div className="w-24 h-8 bg-gray-300 dark:bg-gray-600 rounded-full mx-auto"/>
        </div>
      </div>
    </div>
  );
}

// src/lib/components/cards/AnimeCard.svelte
<script lang="ts" module>
  export type AnimeCardStyle =
    | 'default'
    | 'hover-transparent'
    | 'hover'
    | 'transparent'
    | 'long'
    | 'detail'
    | 'episode';

  export interface AnimeCardAirTime {
    show: boolean;
    text: string;
    variant?: 'countdown' | 'scheduled' | 'aired' | 'airing';
  }
</script>

<script lang="ts">
  import type { Snippet } from 'svelte';
  import SafeImage from '$lib/components/primitives/SafeImage.svelte';
  import ScrollingText from '$lib/components/primitives/ScrollingText.svelte';
  import ScrollingTags from '$lib/components/primitives/ScrollingTags.svelte';
  import { STATUS_LABELS } from '$lib/utils/status';
  import { animeHref } from '$lib/services/utils';
  import { realCardTracking, type CardTrackingPort } from './Card.bloc.svelte';

  /**
   * Presentational -- no bloc. Everything it draws arrives as a prop, its title
   * included: whoever owns the title-language preference resolves it (see
   * Card.bloc). The one side effect is the analytics ping on the title link --
   * a report of what the reader just did rather than state this component owns
   * -- and that arrives as the same module's shared port.
   */
  let {
    style = 'default',
    forceListLayout = false,
    title,
    episodes,
    episodeLength,
    year,
    image,
    id,
    // Optional: callers that have not been given the slug yet fall back to
    // /show/<id>, which permanently redirects.
    slug = undefined,
    className = '',
    airTime = undefined,
    entry = null,
    // Episode specific props
    airdate = '',
    episodeTitle = '',
    episodeNumber = '',
    // Tags/genres for card display
    tags = [],
    /** Controls rendered under the metadata on the `detail` and `episode` styles. */
    options,
    track = realCardTracking,
  }: {
    style?: AnimeCardStyle;
    forceListLayout?: boolean;
    title: string;
    episodes: number | string;
    episodeLength: string;
    year: string;
    image: string;
    id: string | null | undefined;
    slug?: string | null | undefined;
    className?: string;
    airTime?: AnimeCardAirTime | undefined;
    entry?: { status?: string } | null;
    airdate?: string;
    episodeTitle?: string;
    episodeNumber?: string;
    tags?: string[];
    options?: Snippet;
    track?: CardTrackingPort;
  } = $props();

  const statusLabels = STATUS_LABELS;

  const cardStyles = {
    default: `w-48 h-72`,
    'hover-transparent': `w-48 h-72 hover:bg-weeb-surface-hover`,
    hover: `w-48 h-72 hover:bg-weeb-surface-hover hover:shadow-lg`,
    transparent: `w-48 h-72 bg-transparent`,
    long: `w-96 h-96`,
    detail: ``,
    episode: ``,
  };

  function getAirTimeColorClasses(variant?: string) {
    switch (variant) {
      case 'countdown': return 'text-weeb-red';
      case 'airing': return 'text-weeb-amber';
      case 'aired': return 'text-weeb-green';
      default: return 'text-weeb-accent-text';
    }
  }

  // Estimate duration based on available data
  function getEstimatedDuration(): { value: string; isEstimate: boolean } {
    // If we have actual duration, use it
    if (episodeLength && episodeLength !== 'Unknown' && episodeLength !== '') {
      return { value: episodeLength, isEstimate: false };
    }

    // Check if it's a short based on tags
    const isShort = tags?.some(tag =>
      tag.toLowerCase().includes('short') ||
      tag.toLowerCase().includes('music')
    );
    if (isShort) {
      return { value: '~12 min', isEstimate: true };
    }

    // Check if it's likely a movie (1 episode or movie-related tags)
    const isMovie = tags?.some(tag =>
      tag.toLowerCase().includes('movie')
    ) || (episodes === 1 || episodes === '1');
    if (isMovie) {
      return { value: '~90 min', isEstimate: true };
    }

    // Default to standard TV anime length
    return { value: '~24 min', isEstimate: true };
  }

  // Get episode display
  function getEpisodeDisplay(): { value: string | number; isTBA: boolean } {
    if (episodes && episodes !== 0 && episodes !== '0') {
      return { value: episodes, isTBA: false };
    }
    return { value: 'TBA', isTBA: true };
  }

  const durationDisplay = $derived(getEstimatedDuration());
  const episodeDisplay = $derived(getEpisodeDisplay());
</script>

<div class="flex {forceListLayout ? 'flex-row' : 'sm:flex-row md:flex-col'} rounded-md shadow w-full justify-center transition-all duration-300 {className} relative h-full" style="background: var(--weeb-surface);">
  <!-- Watchlist indicator -->
  {#if entry?.status}
    <div class="watchlist-badge">
      <i class="fas fa-bookmark text-xs mr-1"></i>
      {statusLabels[entry.status] || 'Unknown'}
    </div>
  {/if}

  <a href={animeHref({ id, slug })}
     onclick={() => track(id || '', title)}
     class="flex flex-col {cardStyles[style]} overflow-hidden transition-colors duration-300 {forceListLayout ? 'rounded-l-md h-full flex-shrink-0 flex-grow-0 w-32' : 'flex-shrink sm:flex-shrink md:flex-shrink-0 rounded-l-md lg:rounded-bl-none lg:rounded-t-md'}" style="background: var(--weeb-surface);">
    <SafeImage
            src={image}
            alt={title}
            className={forceListLayout ? 'object-cover h-full relative' : 'aspect-2/3 object-cover w-full h-full relative'}
            fallbackSrc="/assets/not found.jpg"
    />
  </a>

  {#if style === 'detail'}
    <div class="flex flex-col flex-grow min-w-0 px-4 py-2 h-full relative w-full group">
      <a href={animeHref({ id, slug })} onclick={() => track(id || '', title)} class="flex overflow-hidden flex-col w-full flex-grow">
        <ScrollingText
                text={title}
                className="text-md font-bold text-weeb-fg"
                maxWidth="100%"
        />

        <ScrollingTags {tags} className="mt-1" />

        <div class="flex flex-col space-y-2 text-md font-normal mt-2 items-start text-weeb-fg-secondary">
          <div class="flex items-center">
            <i class="fas fa-tv text-sm w-4 text-center mr-2"></i>
            <span class={episodeDisplay.isTBA ? 'text-weeb-fg-muted' : ''}>{episodeDisplay.value}</span>
          </div>
          <div class="flex items-center" title={durationDisplay.isEstimate ? 'Estimated duration' : ''}>
            <i class="fas fa-clock text-sm w-4 text-center mr-2"></i>
            <span class="{durationDisplay.isEstimate ? 'text-weeb-fg-muted italic' : ''}">{durationDisplay.value}</span>
          </div>
          <div class="flex items-center">
            <i class="fas fa-calendar text-sm w-4 text-center mr-2"></i>
            <span class={year === 'TBA' || !year ? 'text-weeb-fg-muted' : ''}>{year || 'TBA'}</span>
          </div>
          {#if airTime?.show}
            <div class="flex items-center {getAirTimeColorClasses(airTime.variant)}">
              <i class="fas fa-broadcast-tower text-sm w-4 text-center mr-2"></i>
              <span class="text-xs font-medium">{airTime.text}</span>
            </div>
          {/if}
        </div>
      </a>

      <!-- Always positioned at bottom -->
      <div class="flex flex-wrap gap-2 options w-full mt-auto pt-3 {forceListLayout ? 'justify-start' : 'justify-center'}">
        {@render options?.()}
      </div>
    </div>
  {/if}

  {#if style === 'episode'}
    <div class="flex flex-col flex-grow min-w-0 px-4 py-2 h-full relative w-full group">
      <a href={animeHref({ id, slug })} onclick={() => track(id || '', title)} class="flex flex-col overflow-hidden w-full flex-grow">
        <ScrollingText
                text={title}
                className="text-md font-bold text-weeb-fg"
                maxWidth="100%"
        />

        <ScrollingTags {tags} className="mt-1" />

        <ScrollingText
                text={episodeTitle}
                className="text-md font-normal text-weeb-fg mt-1"
                maxWidth="100%"
        />

        <div class="flex flex-col w-full justify-between space-y-2">
          <span class="flex-grow text-md text-base space-x-4 text-weeb-fg-muted">
            <span>episode {episodeNumber}</span>
          </span>

          {#if airTime?.show}
            <div class="flex items-center {getAirTimeColorClasses(airTime.variant)}">
              <i class="fas fa-broadcast-tower text-sm w-4 text-center mr-2"></i>
              <span class="text-xs font-medium">{airTime.text}</span>
            </div>
          {:else}
            <span class="flex-grow text-md text-base space-x-4 text-weeb-fg-muted">
              <span>{airdate}</span>
            </span>
          {/if}
        </div>
      </a>

      <!-- Always positioned at bottom -->
      <div class="flex flex-wrap gap-2 options w-full mt-auto pt-3 {forceListLayout ? 'justify-start' : 'justify-center'}">
        {@render options?.()}
      </div>
    </div>
  {/if}
</div>

<style>
  .watchlist-badge {
    position: absolute;
    top: 8px;
    left: 8px;
    background: var(--weeb-accent);
    color: white;
    font-size: 12px;
    padding: 2px 8px;
    border-radius: var(--weeb-radius-full, 9999px);
    font-weight: 500;
    box-shadow: var(--weeb-shadow-card);
    z-index: 10;
  }
</style>
