// src/svelte/components/Modal.svelte
<script lang="ts">
  import { createEventDispatcher, onMount } from 'svelte';

  export let isOpen = false;
  export let showCloseButton = true;
  export let backdropCloseable = true;
  export let className = '';

  const dispatch = createEventDispatcher();

  function closeModal() {
    dispatch('close');
  }

  function handleBackdropClick(e: MouseEvent) {
    if (backdropCloseable && e.target === e.currentTarget) {
      closeModal();
    }
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Escape' && isOpen) {
      closeModal();
    }
  }

  // Prevent body scroll when modal is open
  $: if (typeof document !== 'undefined') {
    if (isOpen) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = '';
    }
  }
</script>

<svelte:window on:keydown={handleKeydown} />

{#if isOpen}
  <!-- Backdrop -->
  <div
    class="fixed inset-0 bg-black/40 z-50 transition-opacity duration-300"
    on:click={handleBackdropClick}
    role="dialog"
    aria-modal="true"
  >
    <!-- Modal Content -->
    <div class="fixed inset-0 z-50 overflow-y-auto">
      <div class="flex min-h-full items-center justify-center p-4 text-center sm:p-0">
        <div
          class="relative transform overflow-hidden rounded-lg bg-white dark:bg-gray-800 px-4 pb-4 pt-5 text-left shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-lg sm:p-6 {className}"
          on:click|stopPropagation
        >
          {#if showCloseButton}
            <!-- Close button -->
            <button
              type="button"
              class="absolute right-4 top-4 text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 transition-colors"
              on:click={closeModal}
              aria-label="Close modal"
            >
              <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          {/if}

          <!-- Modal content -->
          <slot />
        </div>
      </div>
    </div>
  </div>
{/if}

// src/components/Modal/Modal.tsx
// react functional component with children
import {Fragment} from "react";
import {Dialog, Transition} from "@headlessui/react";
import Button, {ButtonColor} from "../Button";

export interface ModalProps {
  title: string
  children: React.ReactNode
  isOpen: boolean
  closeFn: () => void
  options?: {
    label: string
    onClick: () => void
  }[]

  className?: string
}

export default function Modal({children, title, isOpen, closeFn, options, className}: ModalProps) {

  return (
    <Transition appear show={isOpen} as={Fragment}>

      <Dialog as="div" className="fixed z-50" onClose={closeFn}>
        <Transition.Child
          as={Fragment}
          enter="ease-out duration-300"
          enterFrom="opacity-0"
          enterTo="opacity-100"
          leave="ease-in duration-200"
          leaveFrom="opacity-100"
          leaveTo="opacity-0"
        >
          <div className={`fixed inset-0 bg-black bg-opacity-25 ${className || ''}`}/>
        </Transition.Child>

        <div className="fixed inset-0 overflow-y-auto">
          <div className="flex min-h-full items-center justify-center p-4 text-center">
            <Dialog.Panel
              className="transform rounded-2xl text-left align-middle shadow-xl transition-all bg-white dark:bg-gray-800">
              <Dialog.Title>{title}</Dialog.Title>
              <div className="flex justify-between flex-col flex-no-wrap">
                <div className="mt-2">
                  {children}
                </div>
                <div className="flex justify-end mt-4">
                  {options && options.map((option, index) => (
                    <Button key={index} color={ButtonColor.blue} label={option.label} showLabel
                            onClick={option.onClick}/>
                  ))}
                </div>
              </div>
            </Dialog.Panel>
          </div>
        </div>
      </Dialog>
    </Transition>
  )
}
