// src/routes/profile/settings/+page.svelte
<script lang="ts">
  import Seo from '$lib/Seo.svelte';
  import { faUser, faEnvelope, faGlobe, faArrowLeft } from '@fortawesome/free-solid-svg-icons';
  import Fa from 'svelte-fa';
  import Button from '../../../svelte/components/Button.svelte';
  import ErrorBanner from '../../../svelte/components/ErrorBanner.svelte';
  import FormInput from '../../../svelte/components/FormInput.svelte';
  import Skeleton from '../../../svelte/components/Skeleton.svelte';
  import { ProfileSettingsBloc, type ProfileFormField } from '../../../svelte/components/ProfileSettings.bloc.svelte';

  /**
   * The settings form.
   *
   * A view over the bloc: it holds the edits, decides what has actually changed
   * and owns the save; this renders the fields and forwards what was typed.
   */
  let { bloc = new ProfileSettingsBloc() }: { bloc?: ProfileSettingsBloc } = $props();

  /** FormInput reports the value plus the event it came from, which names the field. */
  function onField(detail: { value: string; originalEvent: Event }): void {
    const name = (detail.originalEvent.target as HTMLInputElement).name as ProfileFormField;
    bloc.setField(name, detail.value);
  }
</script>

<Seo
  title="Profile Settings"
  description="Update your personal information and preferences."
  noIndex={true}
/>

{#if bloc.isLoading}
  <div class="max-w-2xl mx-auto p-6">
    <div class="mb-6 space-y-4">
      <Skeleton className="h-4 w-32" />
      <Skeleton className="h-8 w-48" />
      <Skeleton className="h-4 w-64" />
    </div>
    <div class="bg-weeb-surface shadow rounded-lg p-6">
      <div class="space-y-6">
        {#each Array(5) as _}
          <Skeleton className="h-16 w-full" />
        {/each}
      </div>
    </div>
  </div>
{:else if bloc.hasUser}
  <div class="max-w-2xl mx-auto p-6">
    <div class="mb-6">
      <a
        href="/profile"
        class="inline-flex items-center text-weeb-accent-text hover:text-weeb-accent-text transition-colors mb-4"
      >
        <Fa icon={faArrowLeft} class="mr-2" />
        Back to Profile
      </a>
      <h1 class="text-2xl font-bold text-weeb-fg">Profile Settings</h1>
      <p class="text-weeb-fg-muted mt-1">Update your personal information and preferences</p>
    </div>

    <div class="bg-weeb-surface shadow rounded-lg p-6 transition-colors duration-300">
      <form
        class="space-y-6"
        onsubmit={(e) => {
          e.preventDefault();
          bloc.submit();
        }}
      >
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
          <FormInput
            id="firstname"
            name="firstname"
            type="text"
            value={bloc.form.firstname}
            onInput={onField}
            placeholder="First Name"
            label="First Name"
            icon={faUser}
            required={false}
          />

          <FormInput
            id="lastname"
            name="lastname"
            type="text"
            value={bloc.form.lastname}
            onInput={onField}
            placeholder="Last Name"
            label="Last Name"
            icon={faUser}
            required={false}
          />
        </div>

        <FormInput
          id="username"
          name="username"
          type="text"
          value={bloc.form.username}
          onInput={onField}
          placeholder="Username"
          label="Username"
          icon={faUser}
          error={bloc.usernameError}
          required={true}
        />

        <FormInput
          id="email"
          name="email"
          type="email"
          value={bloc.form.email}
          onInput={onField}
          placeholder="Email Address (optional)"
          label="Email Address"
          icon={faEnvelope}
        />

        <div>
          <label for="language" class="block text-sm font-medium text-weeb-fg-secondary mb-2">
            <Fa icon={faGlobe} class="mr-2" />
            Language
          </label>
          <select
            id="language"
            name="language"
            value={bloc.form.language}
            onchange={(e) => bloc.setLanguage(e.currentTarget.value)}
            class="w-full px-3 py-2 border border-weeb-border rounded-md shadow-sm bg-weeb-surface text-weeb-fg focus:outline-none focus:ring-2 focus:ring-weeb-accent focus:border-weeb-accent transition-colors duration-200"
          >
            {#each bloc.languages as language (language.value)}
              <option value={language.value}>{language.label}</option>
            {/each}
          </select>
        </div>

        <!-- Public page customization -->
        <div class="pt-2">
          <h2 class="text-sm font-semibold text-weeb-fg mb-1">Your public page</h2>
          <p class="text-xs text-weeb-fg-muted mb-4">
            How <span class="font-mono">/u/{bloc.form.username || 'you'}</span> looks to anyone who visits.
          </p>

          <div>
            <label for="bio" class="block text-sm font-medium text-weeb-fg-secondary mb-2">Bio</label>
            <textarea
              id="bio"
              name="bio"
              rows="2"
              maxlength={bloc.bioLimit}
              value={bloc.form.bio}
              oninput={(e) => bloc.setField('bio', e.currentTarget.value)}
              placeholder="A line about you"
              class="w-full px-3 py-2 border border-weeb-border rounded-md bg-weeb-surface text-weeb-fg placeholder:text-weeb-fg-muted focus:outline-none focus:ring-2 focus:ring-weeb-accent focus:border-weeb-accent transition-colors resize-none"
            ></textarea>
            <div class="mt-1 text-right text-xs text-weeb-fg-muted font-mono">
              {bloc.bioLength}/{bloc.bioLimit}
            </div>
          </div>

          <div class="mt-4">
            <span class="block text-sm font-medium text-weeb-fg-secondary mb-2">Accent colour</span>
            <div class="flex flex-wrap gap-2">
              {#each bloc.accents as accent (accent.name)}
                <button
                  type="button"
                  title={accent.label}
                  aria-label={accent.label}
                  aria-pressed={bloc.isAccentSelected(accent.name)}
                  onclick={() => bloc.selectAccent(accent.name)}
                  class="w-8 h-8 rounded-full transition-transform hover:scale-110 {bloc.isAccentSelected(accent.name) ? 'ring-2 ring-offset-2 ring-offset-weeb-bg ring-weeb-fg' : ''}"
                  style="background: {accent.value}"
                ></button>
              {/each}
            </div>
          </div>

          <div class="mt-4 flex items-center justify-between gap-4">
            <div>
              <span class="block text-sm font-medium text-weeb-fg-secondary">Show my lists</span>
              <span class="block text-xs text-weeb-fg-muted">Let visitors see your watch and read lists. Your header is always public.</span>
            </div>
            <button
              type="button"
              role="switch"
              aria-checked={bloc.form.listsPublic}
              aria-label="Show my lists on my public page"
              onclick={() => bloc.toggleListsPublic()}
              class="relative shrink-0 w-11 h-6 rounded-full transition-colors {bloc.form.listsPublic ? 'bg-weeb-accent' : 'bg-weeb-surface-hover'}"
            >
              <span class="absolute top-0.5 left-0.5 w-5 h-5 rounded-full bg-white transition-transform {bloc.form.listsPublic ? 'translate-x-5' : ''}"></span>
            </button>
          </div>
        </div>

        {#if bloc.successMessage}
          <ErrorBanner severity="success" message={bloc.successMessage} />
        {/if}

        {#if bloc.errorMessage}
          <ErrorBanner message={bloc.errorMessage} />
        {/if}

        <div class="flex gap-4 pt-4">
          <Button
            color="blue"
            label="Save Changes"
            onClick={() => {}}
            showLabel={true}
            status={bloc.isSaving ? 'loading' : 'idle'}
            className="flex-1"
          />
          <a
            href="/profile"
            class="px-4 py-2 border border-weeb-border rounded-md text-weeb-fg-secondary hover:bg-weeb-surface-hover transition-colors duration-200 inline-flex items-center justify-center"
          >
            Cancel
          </a>
        </div>
      </form>
    </div>
  </div>
{/if}

// src/views/profile/settings.tsx
import React, { useState } from 'react';
import { useNavigate } from '../../utils/navigation';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faUser, faEnvelope, faGlobe, faArrowLeft, faCheck } from '@fortawesome/free-solid-svg-icons';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { getUser, updateUserDetails } from '../../services/queries';
import { type UpdateUserInput, Language } from '../../gql/graphql';
import Button, { ButtonColor } from '../../components/Button/Button';
import FormInput from '../../components/FormInput';
import Loader from '../../components/Loader';
import debug from '../../utils/debug';

const ProfileSettings: React.FC = () => {
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const [successMessage, setSuccessMessage] = useState<string>('');
  const [errorMessage, setErrorMessage] = useState<string>('');

  const { data: user, isLoading } = useQuery(getUser());

  const [formData, setFormData] = useState<UpdateUserInput>({
    firstname: user?.firstname || '',
    lastname: user?.lastname || '',
    username: user?.username || '',
    email: user?.email || '',
    language: user?.language || Language.En
  });

  // Update form data when user data is loaded
  React.useEffect(() => {
    if (user) {
      setFormData({
        firstname: user.firstname,
        lastname: user.lastname,
        username: user.username,
        email: user.email || '',
        language: user.language
      });
    }
  }, [user]);

  const updateMutation = useMutation({
    ...updateUserDetails(),
    onSuccess: (updatedUser) => {
      debug.success('Profile updated successfully');
      setSuccessMessage('Profile updated successfully!');
      setErrorMessage('');
      
      // Update the cached user data
      queryClient.setQueryData(['user'], updatedUser);
      
      // Clear success message after 3 seconds
      setTimeout(() => {
        setSuccessMessage('');
      }, 3000);
    },
    onError: (error: any) => {
      debug.error('Profile update failed', error);
      setErrorMessage(error?.message || 'Failed to update profile. Please try again.');
      setSuccessMessage('');
    }
  });

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: name === 'language' ? value as Language : value
    }));
    
    // Clear messages when user starts typing
    if (errorMessage) setErrorMessage('');
    if (successMessage) setSuccessMessage('');
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    // Basic validation
    if (!formData.firstname?.trim() || !formData.lastname?.trim() || !formData.username?.trim()) {
      setErrorMessage('First name, last name, and username are required.');
      return;
    }

    // Only send fields that have changed
    const changedFields: UpdateUserInput = {};
    if (formData.firstname !== user?.firstname) changedFields.firstname = formData.firstname;
    if (formData.lastname !== user?.lastname) changedFields.lastname = formData.lastname;
    if (formData.username !== user?.username) changedFields.username = formData.username;
    if (formData.email !== user?.email) changedFields.email = formData.email;
    if (formData.language !== user?.language) changedFields.language = formData.language;

    // If nothing changed, show message
    if (Object.keys(changedFields).length === 0) {
      setSuccessMessage('No changes to save.');
      return;
    }

    setErrorMessage('');
    updateMutation.mutate(changedFields);
  };

  if (isLoading || !user) return <Loader />;

  return (
    <div className="max-w-2xl mx-auto p-6">
      <div className="mb-6">
        <a
          href="/profile"
          className="inline-flex items-center text-blue-600 dark:text-blue-400 hover:text-blue-500 dark:hover:text-blue-300 transition-colors mb-4"
        >
          <FontAwesomeIcon icon={faArrowLeft} className="mr-2" />
          Back to Profile
        </a>
        <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Profile Settings</h1>
        <p className="text-gray-600 dark:text-gray-400 mt-1">Update your personal information and preferences</p>
      </div>

      <div className="bg-white dark:bg-gray-800 shadow rounded-lg p-6 transition-colors duration-300">
        <form onSubmit={handleSubmit} className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <FormInput
              id="firstname"
              name="firstname"
              type="text"
              value={formData.firstname || ''}
              onChange={handleInputChange}
              placeholder="First Name"
              label="First Name"
              icon={faUser}
              required
            />

            <FormInput
              id="lastname"
              name="lastname"
              type="text"
              value={formData.lastname || ''}
              onChange={handleInputChange}
              placeholder="Last Name"
              label="Last Name"
              icon={faUser}
              required
            />
          </div>

          <FormInput
            id="username"
            name="username"
            type="text"
            value={formData.username || ''}
            onChange={handleInputChange}
            placeholder="Username"
            label="Username"
            icon={faUser}
            required
          />

          <FormInput
            id="email"
            name="email"
            type="email"
            value={formData.email || ''}
            onChange={handleInputChange}
            placeholder="Email Address (optional)"
            label="Email Address"
            icon={faEnvelope}
          />

          <div>
            <label htmlFor="language" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              <FontAwesomeIcon icon={faGlobe} className="mr-2" />
              Language
            </label>
            <select
              id="language"
              name="language"
              value={formData.language || ''}
              onChange={handleInputChange}
              className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md shadow-sm bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-colors duration-200"
            >
              <option value={Language.En}>English</option>
              <option value={Language.Th}>Thai</option>
            </select>
          </div>

          {successMessage && (
            <div className="bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-800 rounded-md p-3 flex items-center">
              <FontAwesomeIcon icon={faCheck} className="text-green-600 dark:text-green-400 mr-2" />
              <p className="text-sm text-green-600 dark:text-green-400">{successMessage}</p>
            </div>
          )}

          {errorMessage && (
            <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-md p-3">
              <p className="text-sm text-red-600 dark:text-red-400">{errorMessage}</p>
            </div>
          )}

          <div className="flex gap-4 pt-4">
            <Button
              color={ButtonColor.blue}
              label="Save Changes"
              onClick={() => {}}
              showLabel
              status={updateMutation.isLoading ? 'loading' : 'idle'}
              className="flex-1"
            />
            <button
              type="button"
              onClick={() => navigate('/profile')}
              className="px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-md text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors duration-200"
            >
              Cancel
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default ProfileSettings;
