// src/views/CurrentlyAiring/Calendar/index.tsx
import React, { useState, useEffect } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { fetchCurrentlyAiringWithDates } from "../../../services/queries";
import { CurrentlyAiringWithDateQuery } from "../../../gql/graphql";
import Loader from "../../../components/Loader";
import {
  format,
  parseISO,
  startOfMonth,
  endOfMonth,
  startOfWeek,
  endOfWeek,
  eachDayOfInterval,
  isSameDay,
  addMonths,
  subMonths,
  addWeeks,
  subWeeks,
} from "date-fns";
import { utc } from "@date-fns/utc/utc";
import { AnimePopover } from "./AnimePopover";
import StatusButton, {ButtonColor} from "../../../components/Button";

type ViewMode = "month" | "week";

export default function AiringCalendarPage() {
  const [currentDate, setCurrentDate] = useState(new Date());
  const [viewMode, setViewMode] = useState<ViewMode>("month");
  const queryClient = useQueryClient();

  const start =
    viewMode === "month"
      ? startOfWeek(startOfMonth(currentDate), { weekStartsOn: 0 })
      : startOfWeek(currentDate, { weekStartsOn: 0 });

  const end =
    viewMode === "month"
      ? endOfWeek(endOfMonth(currentDate), { weekStartsOn: 0 })
      : endOfWeek(currentDate, { weekStartsOn: 0 });

  const days = eachDayOfInterval({ start, end });

  const { data, isLoading } = useQuery<CurrentlyAiringWithDateQuery>(
    ["currentlyAiring", start.toISOString(), end.toISOString()],
    () => fetchCurrentlyAiringWithDates(start, end).queryFn()
  );

  // Prefetch next & previous date ranges
  useEffect(() => {
    const ranges = [
      {
        start:
          viewMode === "month"
            ? startOfWeek(startOfMonth(subMonths(currentDate, 1)), { weekStartsOn: 0 })
            : startOfWeek(subWeeks(currentDate, 1), { weekStartsOn: 0 }),
        end:
          viewMode === "month"
            ? endOfWeek(endOfMonth(subMonths(currentDate, 1)), { weekStartsOn: 0 })
            : endOfWeek(subWeeks(currentDate, 1), { weekStartsOn: 0 }),
      },
      {
        start:
          viewMode === "month"
            ? startOfWeek(startOfMonth(addMonths(currentDate, 1)), { weekStartsOn: 0 })
            : startOfWeek(addWeeks(currentDate, 1), { weekStartsOn: 0 }),
        end:
          viewMode === "month"
            ? endOfWeek(endOfMonth(addMonths(currentDate, 1)), { weekStartsOn: 0 })
            : endOfWeek(addWeeks(currentDate, 1), { weekStartsOn: 0 }),
      },
    ];

    for (const { start, end } of ranges) {
      queryClient.prefetchQuery(
        ["currentlyAiring", start.toISOString(), end.toISOString()],
        () => fetchCurrentlyAiringWithDates(start, end).queryFn()
      );
    }
  }, [currentDate, viewMode, queryClient]);

  if (isLoading || !data) return <Loader />;

  const animeByDate: Record<string, typeof data.currentlyAiring> = {};
  for (const anime of data.currentlyAiring || []) {
    for (const episode of anime.episodes || []) {
      const airDate = episode.airDate;
      if (!airDate) continue;

      const key = format(parseISO(airDate, { in: utc }), "yyyy-MM-dd", { in: utc });
      if (!animeByDate[key]) animeByDate[key] = [];

      (animeByDate[key] || []).push({
        ...anime,
        episodes: [episode], // Pass single episode as array for HeroBanner
      });
    }
  }

  const isTodayVisible = (day: Date) =>
    currentDate.getMonth() === new Date().getMonth() && isSameDay(day, new Date());

  const goPrev = () => {
    setCurrentDate((prev) =>
      viewMode === "month" ? subMonths(prev, 1) : subWeeks(prev, 1)
    );
  };

  const goNext = () => {
    setCurrentDate((prev) =>
      viewMode === "month" ? addMonths(prev, 1) : addWeeks(prev, 1)
    );
  };

  return (
    <div className="max-w-screen-xl mx-auto px-4 py-6 relative">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-4">
        <div className="flex gap-2">
          <StatusButton
            label="Month"
            color={viewMode === "month" ? ButtonColor.blue : ButtonColor.transparent}
            onClick={() => setViewMode("month")}
            className="px-3 py-1 rounded"
          />

          <StatusButton
            label="Week"
            color={viewMode === "week" ? ButtonColor.blue : ButtonColor.transparent}
            onClick={() => setViewMode("week")}
            className="px-3 py-1 rounded ml-2"
          />
        </div>

        <div className="flex items-center gap-4">
          <button onClick={goPrev} className="text-sm text-blue-600 dark:text-blue-400 hover:underline transition-colors duration-300">
            ← Previous
          </button>
          <h1 className="text-xl font-bold text-gray-900 dark:text-gray-100">
            {viewMode === "month"
              ? format(currentDate, "MMMM yyyy")
              : `Week of ${format(start, "MMM d")}`}
          </h1>
          <button onClick={goNext} className="text-sm text-blue-600 dark:text-blue-400 hover:underline transition-colors duration-300">
            Next →
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 lg:grid-cols-7 gap-px bg-gray-200 dark:bg-gray-600 border border-gray-300 dark:border-gray-600 rounded-lg overflow-hidden text-sm relative z-0 transition-colors duration-300">
        {/* Day headers for desktop only */}
        {["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map((day) => (
          <div
            key={day}
            className="hidden lg:block bg-gray-50 dark:bg-gray-700 py-2 px-2 text-center font-medium text-gray-700 dark:text-gray-300 border-b border-gray-200 dark:border-gray-600 transition-colors duration-300"
          >
            {day}
          </div>
        ))}

        {/* Calendar days */}
        {days.map((day) => {
          const dateKey = format(day, "yyyy-MM-dd", { in: utc });
          const entries = animeByDate[dateKey] || [];
          const isToday = isTodayVisible(day);

          return (
            <div
              key={dateKey}
              className={`bg-white dark:bg-gray-800 p-2 transition-colors duration-300 ${
                viewMode === "month" ? "min-h-[140px]" : ""
              } flex flex-col justify-start border border-gray-100 dark:border-gray-600 ${
                isToday ? "bg-blue-50 dark:bg-blue-900/30 ring-2 ring-blue-400 dark:ring-blue-500" : ""
              }`}
            >
              <div className="text-xs font-semibold text-gray-800 dark:text-gray-200 mb-1 flex items-center gap-1">
                <span>{format(day, "d", { in: utc })}</span>
                <span className="text-gray-500 dark:text-gray-400 text-xs block lg:hidden">
                  ({format(day, "EEE")})
                </span>
              </div>
              <div
                className={`flex flex-col gap-1 pr-1 ${
                  viewMode === "month"
                    ? "overflow-y-auto scrollbar-thin scrollbar-thumb-gray-300 dark:scrollbar-thumb-gray-500 scrollbar-track-transparent"
                    : ""
                }`}
              >
                {entries.map((anime, index) => (
                  <AnimePopover anime={anime} key={`${anime.id}-${index}`} />
                ))}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}

// src/routes/airing/calendar/+page.svelte
<script lang="ts">
  import Seo from '$lib/Seo.svelte';
  import Tabs from '../../../svelte/components/Tabs.svelte';
  import Skeleton from '../../../svelte/components/Skeleton.svelte';
  import EmptyState from '../../../svelte/components/EmptyState.svelte';
  import ErrorBanner from '../../../svelte/components/ErrorBanner.svelte';
  import AnimeCalendarPopover from '../../../svelte/components/AnimeCalendarPopover.svelte';
  import { AiringCalendarBloc } from '../../../svelte/components/AiringCalendar.bloc.svelte';
  import type { AiringShow } from '../../../svelte/components/CurrentlyAiringPage.schedule';
  import type { TabItem } from '../../../svelte/components/Tabs.svelte';

  /**
   * The airing schedule as a month or week grid.
   *
   * A view over the bloc: it owns the range, the query keyed to it and the
   * per-day bucketing; this renders cells.
   */
  let {
    data,
    bloc = new AiringCalendarBloc({
      source: () => ({ ssrData: data.ssrData ?? null, ssrError: data.ssrError ?? null }),
    }),
  }: {
    data: {
      ssrData?: { currentlyAiring?: AiringShow[] | null } | null;
      ssrError?: string | null;
      /** Kept for the loader's call site; the page reacts to it, nothing else does. */
      isTokenExpired?: boolean;
    };
    bloc?: AiringCalendarBloc;
  } = $props();

  $effect(() => bloc.init());

  const MODES: TabItem[] = [
    { value: 'month', label: 'Month' },
    { value: 'week', label: 'Week' },
  ];

  const WEEKDAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

  const GRID =
    'grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 lg:grid-cols-7 gap-px bg-weeb-surface ' +
    'border border-weeb-border rounded-lg overflow-hidden text-sm relative z-0 ' +
    'transition-colors duration-300';

  const CELL =
    'bg-weeb-surface p-2 transition-colors duration-300 flex flex-col justify-start ' +
    'border border-weeb-border';

  /**
   * A placeholder month should look like a month that has shows in it, not like
   * an empty one, or the grid visibly reflows when the data lands. The counts
   * are a fixed pattern rather than nine hand-copied cells: same shape, one
   * place to change it.
   */
  function placeholderRows(index: number): number {
    return [1, 2, 3, 1, 4, 1, 1][index % 7];
  }
</script>

<Seo
  title="Airing Calendar"
  description="View anime airing schedule in a calendar format. See episodes by date and plan your watching schedule."
/>

<div class="max-w-screen-xl mx-auto relative py-8 px-0">
  <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-4">
    <Tabs
      items={MODES}
      value={bloc.viewMode}
      onChange={(value) => bloc.selectViewMode(value)}
      variant="segmented"
      ariaLabel="Month or week"
    />

    <div class="flex items-center gap-4">
      <button
        type="button"
        onclick={() => bloc.previous()}
        class="text-sm text-weeb-accent-text hover:underline transition-colors duration-300"
      >
        ← Previous
      </button>
      <h1 class="text-xl font-bold text-weeb-fg">{bloc.title}</h1>
      <button
        type="button"
        onclick={() => bloc.next()}
        class="text-sm text-weeb-accent-text hover:underline transition-colors duration-300"
      >
        Next →
      </button>
    </div>
  </div>

  {#if bloc.isError}
    <ErrorBanner
      message="Couldn't load the airing calendar."
      detail={bloc.errorDetail}
      retrying={bloc.isRetrying}
      onRetry={() => bloc.retry()}
    />
  {:else if bloc.isLoading}
    <div class={GRID}>
      {#each WEEKDAYS as weekday (weekday)}
        <div
          class="hidden lg:block bg-weeb-bg-elevated py-2 px-2 text-center font-medium text-weeb-fg-secondary border-b border-weeb-border transition-colors duration-300"
        >
          {weekday}
        </div>
      {/each}

      {#each Array(bloc.skeletonCellCount) as _, index (index)}
        <div class="{CELL} min-h-[140px]">
          <div class="text-xs font-semibold text-weeb-fg mb-1 flex items-center gap-1">
            <Skeleton className="h-3 w-4" />
          </div>
          <div class="flex flex-col gap-1 pr-1">
            {#each Array(placeholderRows(index)) as _, row (row)}
              <div class="bg-weeb-surface px-2 py-1 rounded w-full flex flex-col gap-0.5">
                <Skeleton className="h-[14px] w-full bg-weeb-surface-hover" />
                <Skeleton className="h-[10px] w-12 bg-weeb-surface-hover" />
              </div>
            {/each}
          </div>
        </div>
      {/each}
    </div>
  {:else if bloc.isEmpty}
    <EmptyState
      variant="panel"
      heading="Nothing airing"
      message={bloc.isMonthView
        ? 'No episodes are scheduled for this month.'
        : 'No episodes are scheduled for this week.'}
    />
  {:else}
    <div class={GRID}>
      {#each WEEKDAYS as weekday (weekday)}
        <div
          class="hidden lg:block bg-weeb-bg-elevated py-2 px-2 text-center font-medium text-weeb-fg-secondary border-b border-weeb-border transition-colors duration-300"
        >
          {weekday}
        </div>
      {/each}

      {#each bloc.cells as cell (cell.iso)}
        <div
          class="{CELL} {bloc.isMonthView ? 'min-h-[140px]' : ''} {cell.isToday
            ? 'ring-2 ring-weeb-accent'
            : ''}"
        >
          <div class="text-xs font-semibold text-weeb-fg mb-1 flex items-center gap-1">
            <span>{cell.dayNumber}</span>
            <span class="text-weeb-fg-muted text-xs block lg:hidden">({cell.weekdayShort})</span>
          </div>
          <div
            class="flex flex-col gap-1 pr-1 {bloc.isMonthView
              ? 'overflow-y-auto scrollbar-thin scrollbar-thumb-weeb-border scrollbar-track-transparent'
              : ''}"
          >
            {#each cell.entries as anime, index (`${anime.id}-${index}`)}
              <AnimeCalendarPopover {anime} />
            {/each}
          </div>
        </div>
      {/each}
    </div>
  {/if}
</div>
